// Generated by scripts/build.mjs — do not edit by hand.
(function(){
  // Theme bootstrap. Runs synchronously before the rest of the IIFE binds
  // so we never flash the wrong theme. Defaults to dark — the terminal look
  // is built around the dark palette and is the canonical view — but a
  // saved 'light' preference still wins so the toggle stays meaningful.
  try {
    var saved = localStorage.getItem('stonks-theme');
    document.documentElement.setAttribute('data-theme', saved || 'dark');
  } catch (_) {
    document.documentElement.setAttribute('data-theme', 'dark');
  }

  var MANIFEST = window.STONKS_MANIFEST || { symbols: [], narratives: [], recentlyEnded: [], macroHeadlines: [], sectors: {}, spots: {} };
  var SYMBOLS = Array.isArray(MANIFEST.symbols) ? MANIFEST.symbols : [];
  var NARRATIVES = Array.isArray(MANIFEST.narratives) ? MANIFEST.narratives : [];
  var RECENTLY_ENDED = Array.isArray(MANIFEST.recentlyEnded) ? MANIFEST.recentlyEnded : [];
  var MACRO_HEADLINES = Array.isArray(MANIFEST.macroHeadlines) ? MANIFEST.macroHeadlines : [];
  var SECTORS = MANIFEST.sectors || {};
  var SPOTS = MANIFEST.spots || {};
  var RFR = 0.045;
  var CHAIN_CACHE = Object.create(null);
  var state = { symbol: null, spot: null, expirations: [], chains: {}, currentExp: null, news: null, technicals: null, fundamentals: null };
  var evalTimer = null;
  var stickyIO = null;

  function $(id){ return document.getElementById(id); }
  function setStatus(elemId, msg, kind){
    var el = $(elemId); if (!el) return;
    el.textContent = msg || '';
    el.className = 'opt-status' + (kind ? ' ' + kind : '');
  }
  function fmt(n, d){ if (n == null || !isFinite(n)) return '—'; return Number(n).toFixed(d == null ? 2 : d); }
  function fmtPct(n){ if (n == null || !isFinite(n)) return '—'; return n.toFixed(2) + '%'; }
  function fmtMoney(n){ if (n == null || !isFinite(n)) return '—'; return '$' + Number(n).toLocaleString(undefined, {minimumFractionDigits:2, maximumFractionDigits:2}); }
  function escapeHtml(s){
    return String(s).replace(/[&<>"']/g, function(ch){
      return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch];
    });
  }
  function debounce(fn, ms){
    return function(){
      var args = arguments;
      clearTimeout(evalTimer);
      evalTimer = setTimeout(function(){ fn.apply(null, args); }, ms);
    };
  }

  // --- Freshness banner ---------------------------------------------------
  function renderFreshness(){
    var banner = $('freshness-banner');
    var bannerText = $('freshness-text');
    if (!banner || !bannerText) return;
    var iso = banner.getAttribute('data-built-at');
    var built = iso ? new Date(iso) : null;
    if (!built || isNaN(built.getTime())) return;
    var ageH = (Date.now() - built.getTime()) / 3600000;
    function rel(h){
      if (h < 1) { var m = Math.max(1, Math.round(h*60)); return m + ' minute' + (m===1?'':'s') + ' ago'; }
      if (h < 36) { var hh = Math.round(h); return hh + ' hour' + (hh===1?'':'s') + ' ago'; }
      var d = Math.round(h/24); return d + ' day' + (d===1?'':'s') + ' ago';
    }
    var dateLabel = built.toLocaleDateString('en-US', { weekday:'short', month:'short', day:'numeric', timeZone:'America/New_York' });
    banner.classList.remove('warn','bad');
    if (ageH > 24*7) {
      banner.classList.add('bad');
      bannerText.innerHTML = 'Very stale — last refreshed ' + dateLabel + '. <span class="freshness-detail">Verify quotes on your broker before trading.</span>';
    } else if (ageH > 36) {
      banner.classList.add('warn');
      bannerText.innerHTML = 'Stale data — last refreshed ' + dateLabel + '. <span class="freshness-detail">Verify quotes on your broker before trading.</span>';
    } else {
      bannerText.innerHTML = 'Refreshed ' + rel(ageH) + ' <span class="freshness-detail">· end-of-session quotes from Yahoo</span>';
    }
  }

  // --- Math: Black-Scholes ------------------------------------------------
  function npdf(x){ return Math.exp(-0.5*x*x) / Math.sqrt(2*Math.PI); }
  function ncdf(x){
    var b1=0.319381530, b2=-0.356563782, b3=1.781477937, b4=-1.821255978, b5=1.330274429;
    var a = Math.abs(x), t = 1/(1 + 0.2316419*a);
    var poly = ((((b5*t + b4)*t + b3)*t + b2)*t + b1) * t;
    var p = 1 - npdf(a)*poly;
    return x < 0 ? 1-p : p;
  }
  function greeks(type, S, K, T, sigma, r){
    if (!(S>0 && K>0 && T>0 && sigma>0)) return null;
    var sqrtT = Math.sqrt(T);
    var d1 = (Math.log(S/K) + (r + 0.5*sigma*sigma)*T) / (sigma*sqrtT);
    var d2 = d1 - sigma*sqrtT;
    var delta = type === 'call' ? ncdf(d1) : ncdf(d1) - 1;
    var thetaYr = type === 'call'
      ? -S*npdf(d1)*sigma/(2*sqrtT) - r*K*Math.exp(-r*T)*ncdf(d2)
      : -S*npdf(d1)*sigma/(2*sqrtT) + r*K*Math.exp(-r*T)*ncdf(-d2);
    var gamma = npdf(d1) / (S*sigma*sqrtT);
    var vega = S*npdf(d1)*sqrtT / 100;
    return { delta: delta, thetaDay: thetaYr/365, gamma: gamma, vega: vega };
  }

  // --- Input parsing ------------------------------------------------------
  function parseLoose(raw){
    if (raw == null) return NaN;
    var s = String(raw).trim();
    if (!s) return NaN;
    s = s.split(/[x×]/i)[0];
    s = s.replace(/[\$,%\s\u00a0]/g, '');
    return parseFloat(s);
  }
  function parseOCC(raw){
    if (raw == null) return null;
    var s = String(raw).trim().toUpperCase();
    var m = s.match(/^([A-Z][A-Z0-9.]{0,5})(\d{2})(\d{2})(\d{2})([CP])(\d{8})$/);
    if (!m) return null;
    var yy = parseInt(m[2],10), mm = parseInt(m[3],10), dd = parseInt(m[4],10);
    if (mm<1||mm>12||dd<1||dd>31) return null;
    var year = 2000 + yy;
    var iso = year + '-' + (mm<10?'0':'') + mm + '-' + (dd<10?'0':'') + dd;
    return { root: m[1], type: m[5]==='C' ? 'call' : 'put', strike: parseInt(m[6],10)/1000, expiryISO: iso };
  }

  // --- Theme toggle -------------------------------------------------------
  function bindThemeToggle(){
    var btn = $('theme-toggle'); if (!btn) return;
    btn.addEventListener('click', function(){
      var current = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
      var next = current === 'dark' ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', next);
      try { localStorage.setItem('stonks-theme', next); } catch (_) {}
    });
  }

  // --- Combobox ----------------------------------------------------------
  var combo = {
    input: null, listbox: null, items: [], activeIdx: -1, open: false,
    init: function(){
      this.input = $('symbol-input');
      this.listbox = $('symbol-listbox');
      if (!this.input || !this.listbox) return;
      var self = this;
      this.input.addEventListener('input', function(){ self.filter(); });
      this.input.addEventListener('focus', function(){ self.filter(); });
      this.input.addEventListener('keydown', function(e){ self.onKey(e); });
      this.input.addEventListener('blur', function(){ setTimeout(function(){ self.close(); }, 120); });
      var clear = $('symbol-clear');
      if (clear) clear.addEventListener('mousedown', function(e){
        e.preventDefault(); self.input.value = ''; self.input.focus(); self.filter();
      });
      this.listbox.addEventListener('mousedown', function(e){
        var li = e.target.closest && e.target.closest('li[data-sym]');
        if (!li) return;
        e.preventDefault();
        self.commit(li.getAttribute('data-sym'));
      });
    },
    rank: function(q){
      q = (q||'').trim().toUpperCase();
      if (!q) return SYMBOLS.slice(0, 50);
      var prefix = [], contains = [], sector = [];
      for (var i=0; i<SYMBOLS.length; i++){
        var sym = SYMBOLS[i];
        var sec = (SECTORS[sym] || '').toUpperCase();
        if (sym.indexOf(q) === 0) prefix.push(sym);
        else if (sym.indexOf(q) >= 0) contains.push(sym);
        else if (sec.indexOf(q) >= 0) sector.push(sym);
      }
      return prefix.concat(contains, sector).slice(0, 50);
    },
    filter: function(){
      var matches = this.rank(this.input.value);
      this.items = matches;
      if (!matches.length){
        this.listbox.innerHTML = '<li class="combo-empty">No matches</li>';
      } else {
        var html = '';
        for (var i=0; i<matches.length; i++){
          var sym = matches[i];
          var sec = SECTORS[sym] || '';
          var spot = SPOTS[sym];
          html += '<li role="option" data-sym="' + sym + '" id="combo-opt-' + sym + '">' +
            '<span class="combo-sym">' + sym + '</span>' +
            '<span class="combo-spot">' + (spot != null ? fmtMoney(spot) : '') + '</span>' +
            '<span class="combo-sector">' + escapeHtml(sec) + '</span>' +
          '</li>';
        }
        this.listbox.innerHTML = html;
      }
      this.activeIdx = -1;
      this.show();
    },
    show: function(){
      this.listbox.hidden = false;
      this.input.setAttribute('aria-expanded', 'true');
      this.open = true;
    },
    close: function(){
      this.listbox.hidden = true;
      this.input.setAttribute('aria-expanded', 'false');
      this.input.removeAttribute('aria-activedescendant');
      this.open = false;
      this.activeIdx = -1;
    },
    move: function(delta){
      if (!this.items.length) return;
      this.activeIdx = (this.activeIdx + delta + this.items.length) % this.items.length;
      var nodes = this.listbox.querySelectorAll('li[data-sym]');
      for (var i=0; i<nodes.length; i++) nodes[i].classList.toggle('is-active', i === this.activeIdx);
      var sym = this.items[this.activeIdx];
      this.input.setAttribute('aria-activedescendant', 'combo-opt-' + sym);
      var active = nodes[this.activeIdx];
      if (active && active.scrollIntoView) active.scrollIntoView({ block: 'nearest' });
    },
    onKey: function(e){
      if (e.key === 'ArrowDown'){ e.preventDefault(); if (!this.open) this.filter(); else this.move(1); }
      else if (e.key === 'ArrowUp'){ e.preventDefault(); this.move(-1); }
      else if (e.key === 'Enter'){
        if (this.activeIdx >= 0){ e.preventDefault(); this.commit(this.items[this.activeIdx]); }
        else if (this.items.length === 1){ e.preventDefault(); this.commit(this.items[0]); }
      }
      else if (e.key === 'Escape'){ this.close(); }
    },
    commit: function(sym){
      if (!sym) return;
      this.input.value = sym;
      this.close();
      // Tear down any in-flight polling from the previous ticker so we
      // don't keep stamping its data into state.
      stopLivePolling();
      liveLastRefreshAt = null;
      state.symbol = sym;
      loadChain();
    }
  };

  // --- Chain controls -----------------------------------------------------
  function fmtExpiryLabel(epoch){
    var d = new Date(epoch*1000);
    return d.toLocaleDateString('en-US', { year:'numeric', month:'short', day:'numeric', timeZone:'America/New_York' });
  }
  function getOptType(){
    var r = document.querySelector('input[name="opt-type"]:checked');
    return r ? r.value : 'call';
  }
  function populateExpiry(){
    var sel = $('opt-expiry'); sel.innerHTML = '';
    state.expirations.forEach(function(epoch){
      var o = document.createElement('option');
      o.value = epoch; o.textContent = fmtExpiryLabel(epoch);
      sel.appendChild(o);
    });
  }
  function populateStrikes(){
    var type = getOptType();
    var chain = state.chains[state.currentExp];
    var sel = $('opt-strike');
    if (!chain){ sel.innerHTML = ''; return; }
    var rows = (type === 'call' ? chain.c : chain.p) || [];
    if (!rows.length){
      sel.innerHTML = '<option disabled>No ' + type + 's available</option>';
      return;
    }
    var spot = state.spot;
    var bestIdx = 0, bestDist = Infinity;
    var parts = new Array(rows.length);
    for (var i=0; i<rows.length; i++){
      var r = rows[i];
      var d = Math.abs((r.s||0) - spot);
      if (d < bestDist){ bestDist = d; bestIdx = i; }
      parts[i] = '<option value="' + i + '">$' + fmt(r.s) + ' · bid ' + fmt(r.b) + ' / ask ' + fmt(r.a) + '</option>';
    }
    sel.innerHTML = parts.join('');
    sel.selectedIndex = bestIdx;
  }
  function findContract(){
    var type = getOptType();
    var chain = state.chains[state.currentExp]; if (!chain) return null;
    var rows = (type === 'call' ? chain.c : chain.p) || [];
    var idx = Number($('opt-strike').value);
    if (!isFinite(idx)) return null;
    return rows[idx] || null;
  }

  // --- Max pain -----------------------------------------------------------
  // For each candidate strike K (union of strikes in the chain) sum the
  // intrinsic value all open calls and puts would have if the underlying
  // closed at K — calls pay (K - strike) when ITM, puts pay (strike - K).
  // The strike that minimizes that total is the "max pain" price: the close
  // where the most aggregate premium expires worthless. Open interest is
  // the weight; volume and IV are ignored — this is purely a positioning
  // snapshot of who is on the hook at expiry.
  function computeMaxPain(chain){
    if (!chain) return null;
    var calls = chain.c || [];
    var puts = chain.p || [];
    var strikeSet = Object.create(null);
    var i;
    for (i = 0; i < calls.length; i++) if (calls[i] && calls[i].s != null) strikeSet[calls[i].s] = true;
    for (i = 0; i < puts.length; i++)  if (puts[i]  && puts[i].s  != null) strikeSet[puts[i].s]  = true;
    var strikes = Object.keys(strikeSet).map(Number).sort(function(a,b){ return a - b; });
    if (!strikes.length) return null;

    var totalCallOI = 0, totalPutOI = 0;
    for (i = 0; i < calls.length; i++) totalCallOI += (calls[i] && calls[i].oi) || 0;
    for (i = 0; i < puts.length; i++)  totalPutOI  += (puts[i]  && puts[i].oi)  || 0;
    if (totalCallOI + totalPutOI <= 0) return null;

    var bestStrike = null, bestPain = Infinity;
    for (var k = 0; k < strikes.length; k++){
      var K = strikes[k];
      var pain = 0;
      for (i = 0; i < calls.length; i++){
        var c = calls[i]; if (!c) continue;
        var coi = c.oi || 0; if (!coi || c.s == null) continue;
        if (K > c.s) pain += (K - c.s) * coi;
      }
      for (i = 0; i < puts.length; i++){
        var p = puts[i]; if (!p) continue;
        var poi = p.oi || 0; if (!poi || p.s == null) continue;
        if (K < p.s) pain += (p.s - K) * poi;
      }
      if (pain < bestPain){ bestPain = pain; bestStrike = K; }
    }
    if (bestStrike == null) return null;
    return {
      strike: bestStrike,
      pain: bestPain,
      totalCallOI: totalCallOI,
      totalPutOI: totalPutOI,
    };
  }
  function renderMaxPain(){
    var box = $('opt-max-pain');
    if (!box) return;
    var chain = state.currentExp ? state.chains[state.currentExp] : null;
    var mp = computeMaxPain(chain);
    if (!mp || mp.strike == null){
      box.hidden = true; box.innerHTML = '';
      return;
    }
    var spot = state.spot;
    var diff = (spot > 0) ? (mp.strike - spot) : null;
    var pct = (spot > 0) ? (diff / spot * 100) : null;
    var dirCls, dirText;
    if (diff == null){
      dirCls = 'flat';
      dirText = '';
    } else if (Math.abs(pct) < 0.25){
      dirCls = 'flat';
      dirText = 'right at spot — sellers want price pinned here';
    } else if (diff < 0){
      dirCls = 'down';
      dirText = '<b>$' + fmt(Math.abs(diff)) + '</b> (' + Math.abs(pct).toFixed(2) + '%) <b>below</b> spot — sellers benefit if price drifts down into expiration';
    } else {
      dirCls = 'up';
      dirText = '<b>$' + fmt(diff) + '</b> (' + pct.toFixed(2) + '%) <b>above</b> spot — sellers benefit if price drifts up into expiration';
    }
    var totalOI = mp.totalCallOI + mp.totalPutOI;
    var callShare = totalOI > 0 ? Math.round(mp.totalCallOI / totalOI * 100) : 0;
    var putShare = 100 - callShare;
    var expLabel = state.currentExp ? fmtExpiryLabel(state.currentExp) : '';
    box.hidden = false;
    box.innerHTML =
      '<div class="opt-max-pain-head">' +
        '<span class="opt-max-pain-label">Max pain</span>' +
        '<span class="opt-max-pain-exp">' + escapeHtml(expLabel) + '</span>' +
        tipChip(TIPS.maxPain) +
      '</div>' +
      '<div class="opt-max-pain-body">' +
        '<span class="opt-max-pain-strike ' + dirCls + '">$' + fmt(mp.strike) + '</span>' +
        (dirText ? '<span class="opt-max-pain-delta ' + dirCls + '">' + dirText + '</span>' : '') +
      '</div>' +
      '<div class="opt-max-pain-meta">' +
        'Based on ' + totalOI.toLocaleString() + ' open contracts · ' +
        callShare + '% calls / ' + putShare + '% puts' +
      '</div>';
  }

  // --- Grading ------------------------------------------------------------
  function gradeSpread(spreadPct){
    if (spreadPct <= 5)  return { label:'Tight',    cls:'good', note:'narrow spread — easy fills' };
    if (spreadPct <= 15) return { label:'Moderate', cls:'fair', note:'spread is workable but costs you on entry/exit' };
    return { label:'Wide', cls:'bad', note:'wide spread — illiquid, expect slippage' };
  }
  function gradeDelta(delta){
    var a = Math.abs(delta);
    if (a >= 0.40 && a <= 0.70) return { label:'Balanced',     cls:'good', note:'good directional sensitivity without paying full intrinsic' };
    if (a >= 0.30 && a < 0.40)  return { label:'Slightly OTM', cls:'fair', note:'cheaper but needs a real move to pay' };
    if (a > 0.70)               return { label:'Deep ITM',     cls:'fair', note:'moves nearly 1:1 with the stock — limited leverage' };
    return { label:'Far OTM', cls:'bad', note:'lottery ticket — most likely expires worthless' };
  }
  function gradeTheta(thetaDay, mid){
    if (mid <= 0 || thetaDay == null) return { label:'—', cls:'fair', note:'theta unavailable' };
    var bleed = Math.abs(thetaDay) / mid * 100;
    if (bleed < 1) return { label:'Slow decay',   cls:'good', note:'~' + bleed.toFixed(2) + '% / day — plenty of runway' };
    if (bleed < 3) return { label:'Normal decay', cls:'fair', note:'~' + bleed.toFixed(2) + '% / day — standard time pressure' };
    return { label:'Bleeding', cls:'bad', note:'~' + bleed.toFixed(2) + '% / day — heavy time decay' };
  }
  function overallVerdict(grades){
    var bad = grades.filter(function(g){ return g.cls === 'bad'; }).length;
    var good = grades.filter(function(g){ return g.cls === 'good'; }).length;
    if (bad >= 2) return { label:'Poor contract', cls:'bad' };
    if (bad === 1) return { label:'Mixed — proceed with caution', cls:'fair' };
    if (good >= 2) return { label:'Good contract', cls:'good' };
    return { label:'Acceptable', cls:'fair' };
  }
  function applyNewsNudge(verdict, news){
    if (!news || !news.sentiment) return verdict;
    if (verdict.cls !== 'fair') return verdict;
    if (news.sentiment === 'bullish') return { label:'Good contract · news tailwind', cls:'good', nudged:true };
    if (news.sentiment === 'bearish') return { label:'Poor contract · news headwind', cls:'bad', nudged:true };
    return verdict;
  }

  var TIPS = {
    spread:     'Gap between bid (what buyers pay) and ask (what sellers want). Wider = you lose more on entry/exit.',
    delta:      'How much the option moves per $1 the stock moves. ~0.50 = at-the-money, ~1.00 = deep ITM, near 0 = far OTM lottery.',
    theta:      'Daily $ the contract loses just from time passing. Higher = the clock is running against you faster.',
    iv:         'Implied volatility — the market\'s guess at how much the stock will move. High IV = expensive premium.',
    gamma:      'How fast delta changes as the stock moves. Higher near ATM and near expiry.',
    vega:       'How much the contract gains/loses per 1 point change in implied volatility.',
    intrinsic:  'Money already baked in: how far in-the-money the contract is. A call $5 ITM has $5 of intrinsic value — that part is yours at expiry no matter what.',
    extrinsic:  'Time + volatility premium on top of intrinsic. Decays to zero by expiry. The bigger this is relative to mid, the more you are paying for hope.',
    breakeven:  'Underlying price the stock needs to reach at expiry just to make back what you paid. Above = profit (for calls); below = profit (for puts).',
    probITM:    'Rough probability the contract finishes in-the-money. Black-Scholes |delta| is the standard proxy — not a guarantee, just the model\'s implied odds.',
    moneyness:  'How far the strike is from the current stock price, in percent. 0% = at the money, negative = below spot, positive = above spot.',
    maxPain:    'Strike at which the total dollar value of all in-the-money options at expiration is minimized — i.e. the most calls and puts expire worthless. Option sellers (market makers) profit most if the stock closes here, so it\'s often called the price they would "want" pinned by expiration. Computed from open interest on the selected expiration; it shifts as OI builds and is a soft target, not a guarantee.',
    rsi:        'Relative Strength Index (14-day). Above 70 = overbought (stretched, prone to a pullback). Below 30 = oversold (washed out, prone to a bounce).',
    macd:       'Moving Average Convergence Divergence (12/26/9). MACD line above signal = bullish momentum; below = bearish. The histogram shows the gap.',
    support:    'Recent price floor — the lowest low over the lookback window. Stocks tend to find buyers around old lows. A break below is a meaningful technical event.',
    resistance: 'Recent price ceiling — the highest high over the lookback window. Stocks tend to stall at old highs. A clean break above is a meaningful technical event.'
  };
  function tipChip(text){
    if (!text) return '';
    var t = text.replace(/"/g, '&quot;');
    return ' <span class="tip" tabindex="0" role="button" aria-label="Explain: ' + t + '" data-tip="' + t + '">?</span>';
  }
  function row(label, value, sub, tip){
    return '<div class="opt-row"><div class="opt-row-label">' + label + tipChip(tip) +
      '</div><div class="opt-row-value">' + value + (sub ? ' <span class="opt-row-sub">' + sub + '</span>' : '') + '</div></div>';
  }
  function gradeChip(g){ return '<span class="opt-grade ' + g.cls + '">' + g.label + '</span>'; }
  function verdictExplainer(cls){
    var msg;
    if (cls === 'good') msg = 'Clean contract. Spread is tight, delta is balanced, theta is manageable. The mechanics are working with you — the rest is direction, sizing, and timing. Cross-check it against the technical signals and news take below before you commit.';
    else if (cls === 'bad') msg = 'Skip or rework. Wide spread or far-OTM delta or heavy theta will eat your edge before the trade plays out. Look for a tighter strike, a more liquid expiry, or a different ticker. If you still like the direction, the manual grader below lets you stress-test alternatives quickly.';
    else msg = 'Workable but not ideal. Read the chip notes below — usually one of spread, delta, or theta is asking you to compromise. Decide whether that trade-off is worth it. The technicals and news take can help break the tie when the mechanics alone are inconclusive.';
    return '<div class="opt-explain ' + cls + '"><b>What this means:</b> ' + msg + '</div>';
  }
  function newsTakeHtml(news, ticker, nudged){
    if (!news || !news.paragraph) return '';
    var sentimentLabel = ({ bullish:'Bullish', neutral:'Neutral', bearish:'Bearish', uncertain:'Uncertain' })[news.sentiment] || 'Neutral';
    var heading = 'AI news take' + (ticker ? (' · ' + escapeHtml(ticker)) : '') + ' · ' + sentimentLabel;
    var note = nudged ? '<div class="opt-news-note">This news context shifted the verdict from <b>Acceptable</b>.</div>' : '';
    var sources = Array.isArray(news.sources) ? news.sources : [];
    var sourcesRow = sources.length
      ? '<div class="opt-news-sources"><span class="opt-news-sources-label">Sources</span>' +
          sources.slice(0, 6).map(function(s){ return '<span class="opt-news-source">' + escapeHtml(s) + '</span>'; }).join('') +
        '</div>'
      : '';
    // headlines may be plain strings (old builds) or {title, publisher} objects.
    var hl = Array.isArray(news.headlines) ? news.headlines : [];
    var hlRow = hl.length
      ? '<details class="opt-news-headlines"><summary>' + hl.length + ' headlines used</summary><ul>' +
          hl.slice(0, 10).map(function(h){
            var title = typeof h === 'string' ? h : (h.title || '');
            var pub = (h && typeof h === 'object') ? (h.publisher || '') : '';
            var rep = (h && typeof h === 'object' && h.reputable) ? ' opt-news-headline-rep' : '';
            var pubTag = pub ? '<span class="opt-news-headline-pub' + rep + '">' + escapeHtml(pub) + '</span>' : '';
            return '<li>' + pubTag + '<span class="opt-news-headline-title">' + escapeHtml(title) + '</span></li>';
          }).join('') +
        '</ul></details>'
      : '';
    return '<div class="opt-news ' + (news.sentiment || 'neutral') + '">' +
      '<div class="opt-news-head">' + heading + '</div>' +
      '<div class="opt-news-body">' + escapeHtml(news.paragraph) + '</div>' +
      sourcesRow +
      hlRow +
      note +
    '</div>';
  }
  function renderNewsPane(){
    var box = $('opt-news-pane');
    if (!box) return;
    if (!state.symbol){ box.innerHTML = ''; return; }
    if (!state.news || !state.news.paragraph){
      box.innerHTML = '<div class="opt-news-empty">No AI news take available for ' + escapeHtml(state.symbol) + ' in this build.</div>';
      return;
    }
    box.innerHTML = newsTakeHtml(state.news, state.symbol, false);
  }
  function renderAnalysisShell(){
    // Show the tabbed analysis container as soon as a ticker is selected.
    // Individual panes still hide themselves when their data is missing.
    var shell = $('opt-analysis');
    if (shell) shell.hidden = !state.symbol;
  }
  function bindTabs(){
    var tabs = document.querySelectorAll('.opt-tab');
    if (!tabs.length) return;
    function selectTab(name){
      try { localStorage.setItem('stonks-tab', name); } catch (_) {}
      tabs.forEach(function(btn){
        var sel = btn.getAttribute('data-tab') === name;
        btn.setAttribute('aria-selected', sel ? 'true' : 'false');
        var paneId = btn.getAttribute('aria-controls');
        var pane = paneId ? document.getElementById(paneId) : null;
        if (pane) pane.hidden = !sel;
      });
    }
    tabs.forEach(function(btn){
      btn.addEventListener('click', function(){ selectTab(btn.getAttribute('data-tab')); });
    });
    var saved = null;
    try { saved = localStorage.getItem('stonks-tab'); } catch (_) {}
    selectTab(saved && ['fund','tech','news'].indexOf(saved) >= 0 ? saved : 'fund');
  }

  function buildResultHtml(input){
    var bid = input.bid, ask = input.ask;
    var mid = (bid != null && ask != null && (bid + ask) > 0) ? (bid + ask) / 2 : (input.last || null);
    var spread = (bid != null && ask != null) ? (ask - bid) : null;
    var spreadPct = (spread != null && mid > 0) ? (spread/mid * 100) : null;
    var iv = input.iv;
    var T = (input.expEpoch*1000 - Date.now()) / (365*24*3600*1000);
    var g = (T > 0 && iv > 0 && input.spot > 0 && input.strike > 0)
      ? greeks(input.type, input.spot, input.strike, T, iv, RFR) : null;

    var sGrade = spreadPct != null ? gradeSpread(spreadPct) : { label:'—', cls:'fair', note:'no quote' };
    var dGrade = g ? gradeDelta(g.delta) : { label:'—', cls:'fair', note:'delta unavailable — IV missing' };
    var tGrade = g ? gradeTheta(g.thetaDay, mid) : { label:'—', cls:'fair', note:'theta unavailable — IV missing' };
    var baseVerdict = overallVerdict([sGrade, dGrade, tGrade]);
    var verdict = applyNewsNudge(baseVerdict, input.news);

    // Derived contract metrics. Intrinsic = how much of the premium is
    // already in-the-money cash. Time value = whatever is left, i.e. what
    // decays. Breakeven = the underlying price the stock needs to reach at
    // expiry just to recover the premium. Probability ITM ≈ |delta| under
    // Black-Scholes — a rough but standard proxy, not a guarantee.
    var intrinsic = null;
    if (input.spot != null && input.strike != null) {
      intrinsic = input.type === 'call'
        ? Math.max(0, input.spot - input.strike)
        : Math.max(0, input.strike - input.spot);
    }
    var extrinsic = (mid != null && intrinsic != null) ? Math.max(0, mid - intrinsic) : null;
    var breakeven = (mid != null && input.strike != null)
      ? (input.type === 'call' ? input.strike + mid : input.strike - mid)
      : null;
    var moneynessPct = (input.spot > 0 && input.strike != null)
      ? (input.spot - input.strike) / input.spot * 100
      : null;
    var probITM = g ? Math.abs(g.delta) * 100 : null;
    var daysToExpiry = Math.max(0, Math.round(T*365));

    var html = '';
    html += '<div class="opt-verdict ' + verdict.cls + '" id="opt-verdict-main">' + verdict.label + '</div>';
    html += verdictExplainer(verdict.cls);
    if (verdict.nudged && input.news && input.news.sentiment){
      var nudgeLabel = ({ bullish:'bullish', bearish:'bearish' })[input.news.sentiment] || 'news';
      html += '<div class="opt-news-note">News context (' + nudgeLabel + ') shifted the verdict from <b>Acceptable</b>. See the News tab below.</div>';
    }
    html += '<div class="opt-contract">' + (input.label || '') + ' · spot $' + fmt(input.spot) + ' · ' + daysToExpiry + ' day' + (daysToExpiry === 1 ? '' : 's') + ' to expiry</div>';
    html += '<div class="opt-grid">';
    html += row('Bid / Ask', '$' + fmt(bid) + ' / $' + fmt(ask));
    html += row('Mid', mid != null ? '$' + fmt(mid) : '—');
    html += row('Spread', spread != null ? ('$' + fmt(spread) + ' (' + fmtPct(spreadPct) + ')') : '—', gradeChip(sGrade), TIPS.spread);
    html += row('Intrinsic value', intrinsic != null ? '$' + fmt(intrinsic) : '—', '', TIPS.intrinsic);
    html += row('Time value', extrinsic != null ? '$' + fmt(extrinsic) : '—', mid > 0 && extrinsic != null ? '<span class="opt-row-mute">' + fmtPct(extrinsic / mid * 100) + ' of mid</span>' : '', TIPS.extrinsic);
    html += row('Breakeven at expiry', breakeven != null ? '$' + fmt(breakeven) : '—', input.spot > 0 && breakeven != null ? '<span class="opt-row-mute">' + (((breakeven - input.spot) / input.spot * 100) >= 0 ? '+' : '') + ((breakeven - input.spot) / input.spot * 100).toFixed(2) + '% from spot</span>' : '', TIPS.breakeven);
    html += row('Moneyness', moneynessPct != null ? ((moneynessPct >= 0 ? '+' : '') + moneynessPct.toFixed(2) + '%') : '—', '', TIPS.moneyness);
    html += row('IV', iv != null ? fmtPct(iv*100) : '—', '', TIPS.iv);
    html += row('Delta', g ? fmt(g.delta, 3) : '—', g ? gradeChip(dGrade) : '', TIPS.delta);
    html += row('Prob. ITM (≈ |delta|)', probITM != null ? probITM.toFixed(1) + '%' : '—', '', TIPS.probITM);
    html += row('Theta / day', g ? '$' + fmt(g.thetaDay, 3) : '—', g ? gradeChip(tGrade) : '', TIPS.theta);
    html += row('Gamma', g ? fmt(g.gamma, 4) : '—', '', TIPS.gamma);
    html += row('Vega (per 1 vol pt)', g ? '$' + fmt(g.vega, 3) : '—', '', TIPS.vega);
    html += row('Open interest', input.oi != null ? String(input.oi) : '—');
    html += row('Volume', input.volume != null ? String(input.volume) : '—');
    html += '</div>';
    html += '<ul class="opt-notes">';
    html += '<li><b>Spread:</b> ' + sGrade.note + '.</li>';
    html += '<li><b>Delta:</b> ' + dGrade.note + '.</li>';
    html += '<li><b>Theta:</b> ' + tGrade.note + '.</li>';
    if (extrinsic != null && mid > 0){
      var extPct = extrinsic / mid * 100;
      var extNote = extPct < 25
        ? 'mostly intrinsic — you are paying for the move that has already happened'
        : extPct < 60
        ? 'a healthy mix of intrinsic and time value — typical at-the-money premium'
        : 'almost all time value — pure bet on the move; theta will grind this down fast';
      html += '<li><b>Premium make-up:</b> ' + extNote + '.</li>';
    }
    if (breakeven != null && input.spot > 0){
      var beMove = (breakeven - input.spot) / input.spot * 100;
      var beAbs = Math.abs(beMove);
      var beNote = beAbs < 2
        ? 'tiny move needed — leverage is modest'
        : beAbs < 6
        ? 'a normal session-or-two move gets you whole'
        : 'a sizable move is required just to break even — the contract is asking for conviction';
      html += '<li><b>Breakeven:</b> ' + beNote + '.</li>';
    }
    if (daysToExpiry > 0 && daysToExpiry <= 3){
      html += '<li><b>Heads-up:</b> only ' + daysToExpiry + ' day' + (daysToExpiry === 1 ? '' : 's') + ' to expiry — gamma is enormous and theta is brutal. Treat this like a same-day trade.</li>';
    }
    html += '</ul>';
    if (input.source === 'chain') {
      var payload = JSON.stringify({
        type: input.type, spot: input.spot, strike: input.strike, expEpoch: input.expEpoch,
        bid: input.bid, ask: input.ask, iv: input.iv,
        oi: input.oi, volume: input.volume,
      }).replace(/'/g, '&apos;');
      html += '<button type="button" class="opt-tweak-btn" data-tweak=\'' + payload + '\'>Tweak in manual form &darr;</button>';
    }
    var disc = input.source === 'manual'
      ? 'Greeks computed locally with Black-Scholes from your IV and a ' + (RFR*100).toFixed(1) + '% risk-free rate. You are the data source — only as accurate as the numbers you typed.'
      : 'Greeks computed with Black-Scholes from Yahoo&apos;s implied vol and a ' + (RFR*100).toFixed(1) + '% risk-free rate. Quotes are end-of-session as of the build timestamp shown above — for information only, not investment advice.';
    html += '<p class="opt-disclaimer">' + disc + '</p>';
    return { html: html, verdict: verdict, contractLabel: input.label || '' };
  }

  function renderStickyVerdict(verdict, label){
    var bar = $('opt-result-sticky');
    if (!bar) return;
    bar.innerHTML = '<span class="opt-verdict-mini ' + verdict.cls + '">' + verdict.label + '</span>' +
      '<span class="opt-contract-mini">' + escapeHtml(label) + '</span>';
  }
  function setupStickyObserver(){
    var verdictEl = $('opt-verdict-main');
    var bar = $('opt-result-sticky');
    if (!verdictEl || !bar || typeof IntersectionObserver === 'undefined') return;
    if (stickyIO) stickyIO.disconnect();
    stickyIO = new IntersectionObserver(function(entries){
      var e = entries[0];
      var stuck = !e.isIntersecting && e.boundingClientRect.top < 0;
      bar.hidden = !stuck;
    }, { threshold: 0, rootMargin: '-56px 0px 0px 0px' });
    stickyIO.observe(verdictEl);
  }

  function evaluate(){
    var c = findContract();
    var resultEl = $('opt-eval-result');
    var stickyEl = $('opt-result-sticky');
    if (!c){
      if (resultEl) resultEl.innerHTML = '';
      if (stickyEl){ stickyEl.hidden = true; stickyEl.innerHTML = ''; }
      return;
    }
    var type = getOptType();
    var label = (state.symbol || '') + ' ' + type.toUpperCase() + ' $' + fmt(c.s) + ' · exp ' + fmtExpiryLabel(state.currentExp);
    var built = buildResultHtml({
      type: type, spot: state.spot, strike: c.s, expEpoch: state.currentExp,
      bid: c.b, ask: c.a, last: c.l, iv: c.iv,
      oi: c.oi, volume: c.v, label: label, source: 'chain',
      news: state.news, ticker: state.symbol
    });
    resultEl.innerHTML = built.html;
    renderStickyVerdict(built.verdict, built.contractLabel);
    setupStickyObserver();
    setStatus('opt-eval-status', '', '');
  }
  var scheduleEvaluate = debounce(evaluate, 80);

  function evaluateManual(ev){
    if (ev) ev.preventDefault();
    var type = $('m-type').value;
    var spot = parseLoose($('m-spot').value);
    var strike = parseLoose($('m-strike').value);
    var expDateStr = $('m-expiry').value;
    var bid = parseLoose($('m-bid').value);
    var ask = parseLoose($('m-ask').value);
    var ivRaw = $('m-iv').value.trim();
    var oiRaw = $('m-oi').value.trim();
    var volRaw = $('m-vol').value.trim();
    var ivPct = parseLoose(ivRaw);
    var oi = parseLoose(oiRaw);
    var vol = parseLoose(volRaw);

    if (!(spot > 0))   { setStatus('opt-manual-status', 'Share price is required.', 'err'); return; }
    if (!(strike > 0)) { setStatus('opt-manual-status', 'Strike price is required.', 'err'); return; }
    if (!expDateStr)   { setStatus('opt-manual-status', 'Expiration date is required.', 'err'); return; }
    if (!isFinite(bid) || !isFinite(ask) || bid < 0 || ask < 0) { setStatus('opt-manual-status', 'Bid and ask are required (enter 0 if you have no quote).', 'err'); return; }
    if (ask < bid) { setStatus('opt-manual-status', 'Ask is below bid — check your numbers.', 'err'); return; }

    var expEpoch = Math.floor(new Date(expDateStr + 'T16:00:00-04:00').getTime()/1000);
    var label = type.toUpperCase() + ' $' + strike + ' · exp ' + expDateStr;
    var built = buildResultHtml({
      type: type, spot: spot, strike: strike, expEpoch: expEpoch,
      bid: bid, ask: ask, last: null,
      iv: (ivRaw && isFinite(ivPct) && ivPct >= 0) ? ivPct/100 : null,
      oi: (oiRaw && isFinite(oi)) ? Math.round(oi) : null,
      volume: (volRaw && isFinite(vol)) ? Math.round(vol) : null,
      label: label, source: 'manual'
    });
    $('opt-manual-result').innerHTML = built.html;
    setStatus('opt-manual-status', 'Graded.', 'ok');
  }

  function onPasteContract(){
    var input = $('m-paste');
    var hint = $('m-paste-hint');
    var raw = input.value;
    if (!raw || !raw.trim()){
      input.classList.remove('err');
      if (hint){ hint.textContent = ''; hint.classList.remove('err'); }
      return;
    }
    var parsed = parseOCC(raw);
    if (!parsed){
      input.classList.add('err');
      if (hint){ hint.textContent = "Doesn't look like an OCC symbol (e.g. AAPL250117C00150000)."; hint.classList.add('err'); }
      return;
    }
    input.classList.remove('err');
    $('m-type').value = parsed.type;
    $('m-strike').value = String(parsed.strike);
    $('m-expiry').value = parsed.expiryISO;
    if (hint){
      hint.textContent = 'Recognised: ' + parsed.root + ' ' + parsed.type.toUpperCase() + ' $' + parsed.strike + ' · exp ' + parsed.expiryISO;
      hint.classList.remove('err');
    }
  }

  function tweakInManual(payloadJson){
    if (!payloadJson) return;
    var p; try { p = JSON.parse(payloadJson); } catch (e) { return; }
    $('m-type').value = p.type === 'put' ? 'put' : 'call';
    if (p.spot != null)   $('m-spot').value   = String(p.spot);
    if (p.strike != null) $('m-strike').value = String(p.strike);
    if (p.expEpoch){
      var d = new Date(p.expEpoch*1000);
      var nyParts = new Intl.DateTimeFormat('en-CA', { timeZone:'America/New_York', year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(d);
      var y='', mo='', da='';
      for (var i=0; i<nyParts.length; i++){
        var part = nyParts[i];
        if (part.type === 'year') y = part.value;
        else if (part.type === 'month') mo = part.value;
        else if (part.type === 'day') da = part.value;
      }
      if (y && mo && da) $('m-expiry').value = y + '-' + mo + '-' + da;
    }
    if (p.bid != null) $('m-bid').value = String(p.bid);
    if (p.ask != null) $('m-ask').value = String(p.ask);
    $('m-iv').value  = (p.iv != null)     ? (p.iv*100).toFixed(2) : '';
    $('m-oi').value  = (p.oi != null)     ? String(p.oi)          : '';
    $('m-vol').value = (p.volume != null) ? String(p.volume)      : '';
    var paste = $('m-paste'); if (paste){ paste.value=''; paste.classList.remove('err'); }
    var hint = $('m-paste-hint'); if (hint){ hint.textContent=''; hint.classList.remove('err'); }
    evaluateManual();
    var section = $('opt-manual-section');
    if (section && section.scrollIntoView) section.scrollIntoView({ behavior:'smooth', block:'start' });
    $('m-bid').focus();
  }

  function fetchChain(symbol){
    if (CHAIN_CACHE[symbol]) return Promise.resolve(CHAIN_CACHE[symbol]);
    var v = (MANIFEST && MANIFEST.builtAtIso) ? '?v=' + encodeURIComponent(MANIFEST.builtAtIso) : '';
    return fetch('data/' + encodeURIComponent(symbol) + '.json' + v, { cache: 'force-cache' })
      .then(function(resp){
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        return resp.json();
      })
      .then(function(data){ CHAIN_CACHE[symbol] = data; return data; });
  }
  function loadChain(){
    var symbol = state.symbol; if (!symbol) return;
    var cached = !!CHAIN_CACHE[symbol];
    // The per-ticker JSON (chain + AI news take + technicals) is fetched here
    // and only here — nothing about a ticker is preloaded before the user
    // commits to it. force-cache keeps re-selects free for the rest of the
    // session.
    setStatus('opt-eval-status', cached ? '' : 'Loading ' + symbol + ' chain, news, technicals + fundamentals…', '');
    fetchChain(symbol).then(function(entry){
      state.spot = entry.spot;
      state.expirations = (entry.expirations || []).slice();
      state.chains = entry.chains || {};
      state.news = entry.news || null;
      state.technicals = entry.technicals || null;
      state.fundamentals = entry.fundamentals || null;
      if (!state.expirations.length){ setStatus('opt-eval-status', 'No expirations for ' + symbol + '.', 'err'); return; }
      state.currentExp = state.expirations[0];
      populateExpiry();
      $('opt-expiry').value = String(state.currentExp);
      populateStrikes();
      renderMaxPain();
      $('opt-chain-row').hidden = false;
      renderTickerNarrativeChips(symbol);
      renderAnalysisShell();
      renderTechnicals(symbol);
      renderFundamentals(symbol);
      renderNewsPane();
      setStatus('opt-eval-status', symbol + ' · spot ' + fmtMoney(state.spot) + ' · ' + state.expirations.length + ' expirations', 'ok');
      evaluate();
      // Kick off the live spot refresh in parallel — the page is already
      // usable with baked data; live just updates spot / Greeks / ATM pick
      // when it arrives. Quietly no-ops if the endpoint or market is closed.
      refreshLiveQuote(symbol);
    }).catch(function(err){
      setStatus('opt-eval-status', 'Failed to load ' + symbol + ': ' + (err && err.message || err), 'err');
    });
  }

  // --- Live spot --------------------------------------------------------
  // Vercel serverless function at /api/quote?symbol=XXX proxies Yahoo's
  // quote endpoint (consent cookie + crumb auth happen server-side). The
  // browser only needs spot + day change to make the grader reflect
  // intraday price; chain quotes and technicals stay on the baked daily
  // build. Cache successful responses for 30 s so rapid re-selects don't
  // re-fire the network call.
  var LIVE_CACHE = Object.create(null);
  var LIVE_TTL_MS = 30000;
  function fmtPctSigned(p){ if (p == null || !isFinite(p)) return ''; return (p >= 0 ? '+' : '') + p.toFixed(2) + '%'; }
  function marketStateLabel(s){
    if (s === 'REGULAR') return { label: 'Live', cls: 'live' };
    if (s === 'PRE') return { label: 'Pre-market', cls: 'pre' };
    if (s === 'POST' || s === 'POSTPOST') return { label: 'After hours', cls: 'post' };
    return { label: 'Delayed', cls: 'delayed' };
  }
  function renderLiveQuote(symbol, q){
    var box = $('opt-live-quote'); if (!box) return;
    if (!q || q.spot == null){ box.hidden = true; box.innerHTML = ''; return; }
    var st = marketStateLabel(q.marketState);
    var changeCls = q.change == null ? '' : (q.change >= 0 ? 'up' : 'down');
    var changeTxt = q.change != null && isFinite(q.change)
      ? ((q.change >= 0 ? '+' : '') + '$' + Math.abs(q.change).toFixed(2) + ' (' + fmtPctSigned(q.changePct) + ')')
      : '';
    box.hidden = false;
    box.innerHTML = '<span class="opt-live-pill ' + st.cls + '">' + st.label + '</span>' +
      '<span class="opt-live-sym">' + escapeHtml(symbol) + '</span>' +
      '<span class="opt-live-spot">' + fmtMoney(q.spot) + '</span>' +
      (changeTxt ? '<span class="opt-live-chg ' + changeCls + '">' + changeTxt + '</span>' : '');
  }
  function refreshLiveQuote(symbol){
    if (!symbol) return;
    var box = $('opt-live-quote');
    var cached = LIVE_CACHE[symbol];
    if (cached && (Date.now() - cached.at) < LIVE_TTL_MS){
      applyLiveQuote(symbol, cached.q);
      return;
    }
    // Show a subtle "checking…" placeholder so the user knows the page is
    // still working in the background — replaced as soon as the call
    // resolves (or fails silently).
    if (box){
      box.hidden = false;
      box.innerHTML = '<span class="opt-live-pill checking">Checking quote…</span>' +
        '<span class="opt-live-sym">' + escapeHtml(symbol) + '</span>';
    }
    fetch('/api/quote?symbol=' + encodeURIComponent(symbol), { cache: 'no-store' })
      .then(function(resp){
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        return resp.json();
      })
      .then(function(q){
        if (!q || q.spot == null) throw new Error('no spot');
        LIVE_CACHE[symbol] = { q: q, at: Date.now() };
        // Bail if the user has already moved to a different ticker.
        if (state.symbol !== symbol) return;
        applyLiveQuote(symbol, q);
      })
      .catch(function(){
        // Silent failure — keep baked data, hide the placeholder.
        if (state.symbol !== symbol) return;
        if (box){ box.hidden = true; box.innerHTML = ''; }
      });
  }
  function applyLiveQuote(symbol, q){
    renderLiveQuote(symbol, q);
    if (q.spot != null && isFinite(q.spot) && q.spot > 0 && q.spot !== state.spot){
      state.spot = q.spot;
      // Re-snap the ATM strike pick to live spot, then regrade. The user's
      // current type/expiry selection is preserved by populateStrikes().
      populateStrikes();
      evaluate();
    }
    // Once we know the market is open, start polling the chain endpoint
    // every 30s so bid/ask/IV/volume stay fresh while the user is on the
    // page. Polling stops automatically on ticker change, market close,
    // tab hide, or page unload.
    startLivePolling();
  }

  // --- Live chain polling -------------------------------------------------
  // The baked per-ticker JSON is a 9am-ET snapshot. During the session,
  // bid/ask spreads tighten, IV moves around, OI/volume tick up, and the
  // spot drifts. /api/chain?symbol=X&exp=Y proxies a fresh Yahoo options
  // pull for the currently-viewed expiration and returns the same compressed
  // shape data/<SYMBOL>.json uses, so we can drop it straight into
  // state.chains[exp] and regrade without any other state changes.
  var CHAIN_POLL_MS = 30000;
  var livePollTimer = null;
  var livePollInFlight = false;
  var liveLastRefreshAt = null;
  function liveRefreshLabel(state){
    if (state === 'REGULAR') return 'Live · auto-refresh 30s';
    if (state === 'PRE') return 'Pre-market · refresh paused';
    if (state === 'POST' || state === 'POSTPOST') return 'After hours · refresh paused';
    return 'Market closed · refresh paused';
  }
  function renderLiveRefreshIndicator(marketState){
    var el = $('opt-live-refresh');
    if (!el) return;
    if (!state.symbol){ el.hidden = true; el.textContent = ''; return; }
    var since = liveLastRefreshAt ? Math.round((Date.now() - liveLastRefreshAt) / 1000) : null;
    var sinceTxt = (since != null && since >= 0 && since < 600)
      ? ' · last update ' + (since < 5 ? 'just now' : since + 's ago')
      : '';
    el.hidden = false;
    el.className = 'opt-live-refresh ' + (marketState === 'REGULAR' ? 'on' : 'off');
    el.textContent = liveRefreshLabel(marketState) + sinceTxt;
  }
  function refreshLiveChain(symbol, exp){
    if (!symbol || !exp) return;
    if (livePollInFlight) return;
    if (state.symbol !== symbol) return;
    livePollInFlight = true;
    fetch('/api/chain?symbol=' + encodeURIComponent(symbol) + '&exp=' + encodeURIComponent(exp), { cache: 'no-store' })
      .then(function(resp){ if (!resp.ok) throw new Error('HTTP ' + resp.status); return resp.json(); })
      .then(function(r){
        livePollInFlight = false;
        if (!r || !r.chain) return;
        if (state.symbol !== symbol) return;
        if (Number(state.currentExp) !== Number(exp)) return;
        // Preserve the strike the user is currently looking at — picking
        // ATM every 30s would yank their selection.
        var prevContract = findContract();
        var prevStrike = prevContract ? prevContract.s : null;
        state.chains[exp] = r.chain;
        if (r.spot != null && isFinite(r.spot) && r.spot > 0) state.spot = r.spot;
        // Keep the live-quote pill in sync — same shape /api/quote returns
        // so renderLiveQuote can reuse its existing branch.
        var pillQ = { spot: r.spot, marketState: r.marketState, change: null, changePct: null };
        LIVE_CACHE[symbol] = { q: pillQ, at: Date.now() };
        renderLiveQuote(symbol, pillQ);
        populateStrikes();
        if (prevStrike != null){
          var type = getOptType();
          var rows = (type === 'call' ? r.chain.c : r.chain.p) || [];
          for (var i = 0; i < rows.length; i++){
            if (rows[i] && rows[i].s === prevStrike){
              $('opt-strike').selectedIndex = i;
              break;
            }
          }
        }
        liveLastRefreshAt = Date.now();
        renderMaxPain();
        evaluate();
        renderLiveRefreshIndicator(r.marketState);
        // Market just closed — stop polling.
        if (r.marketState !== 'REGULAR') stopLivePolling();
      })
      .catch(function(){
        livePollInFlight = false;
        // Silent failure; next interval will try again. Don't tear down
        // the timer on a single hiccup.
      });
  }
  function currentMarketState(){
    var c = LIVE_CACHE[state.symbol];
    return c && c.q ? c.q.marketState : null;
  }
  function startLivePolling(){
    stopLivePolling();
    if (document.hidden) return;
    if (!state.symbol || !state.currentExp) return;
    if (currentMarketState() !== 'REGULAR') {
      renderLiveRefreshIndicator(currentMarketState());
      return;
    }
    renderLiveRefreshIndicator('REGULAR');
    livePollTimer = setInterval(function(){
      if (document.hidden) return;
      if (!state.symbol || !state.currentExp){ stopLivePolling(); return; }
      refreshLiveChain(state.symbol, state.currentExp);
    }, CHAIN_POLL_MS);
  }
  function stopLivePolling(){
    if (livePollTimer){ clearInterval(livePollTimer); livePollTimer = null; }
  }
  // Pause when the tab is hidden — no point burning Yahoo calls for a
  // tab the user can't see. Resume on visibility return.
  document.addEventListener('visibilitychange', function(){
    if (document.hidden) stopLivePolling();
    else startLivePolling();
  });

  // --- Technicals ---------------------------------------------------------
  function rsiState(rsi){
    if (rsi == null || !isFinite(rsi)) return { label:'—', cls:'fair', note:'not enough history' };
    if (rsi >= 70) return { label:'Overbought', cls:'warn',
      note:'stretched — calls here are buying late, puts may catch a mean-reversion bounce' };
    if (rsi <= 30) return { label:'Oversold', cls:'pos',
      note:'washed out — puts here are chasing, calls may catch a bounce' };
    if (rsi >= 55) return { label:'Bullish bias', cls:'pos',
      note:'momentum tilted up — trend traders lean long' };
    if (rsi <= 45) return { label:'Bearish bias', cls:'warn',
      note:'momentum tilted down — trend traders lean short' };
    return { label:'Neutral', cls:'fair', note:'no clear momentum edge either way' };
  }
  function macdState(macd){
    if (!macd) return { label:'—', cls:'fair', note:'not enough history' };
    if (macd.hist > 0 && macd.line > 0) return { label:'Bullish', cls:'pos',
      note:'MACD above signal and above zero — confirmed uptrend momentum' };
    if (macd.hist > 0 && macd.line <= 0) return { label:'Bullish cross', cls:'pos',
      note:'MACD crossed above signal while still under zero — early reversal signal' };
    if (macd.hist < 0 && macd.line < 0) return { label:'Bearish', cls:'warn',
      note:'MACD below signal and below zero — confirmed downtrend momentum' };
    if (macd.hist < 0 && macd.line >= 0) return { label:'Bearish cross', cls:'warn',
      note:'MACD crossed below signal while still above zero — early weakness signal' };
    return { label:'Flat', cls:'fair', note:'line and signal hugging — no clear momentum' };
  }
  function distancePct(level, spot){
    if (level == null || !isFinite(level) || !(spot > 0)) return null;
    return (level - spot) / spot * 100;
  }
  function fmtDistance(level, spot){
    var pct = distancePct(level, spot);
    if (pct == null) return '';
    var sign = pct >= 0 ? '+' : '';
    return sign + pct.toFixed(1) + '% vs spot';
  }
  function techCard(label, valueHtml, stateHtml, noteHtml, tip){
    return '<div class="opt-tech-card">' +
      '<div class="opt-tech-label">' + label + tipChip(tip) + '</div>' +
      '<div class="opt-tech-value">' + valueHtml + '</div>' +
      (stateHtml ? '<div class="opt-tech-state">' + stateHtml + '</div>' : '') +
      (noteHtml ? '<div class="opt-tech-note">' + noteHtml + '</div>' : '') +
    '</div>';
  }
  function renderTechnicals(sym){
    var box = $('opt-technicals');
    var grid = $('opt-tech-grid');
    if (!box || !grid) return;
    var t = state.technicals;
    if (!t){ box.hidden = true; grid.innerHTML = ''; return; }
    var spot = state.spot;
    var rsiSt = rsiState(t.rsi);
    var macdSt = macdState(t.macd);
    var html = '';

    html += techCard(
      'RSI (14)',
      '<span class="opt-tech-num">' + (t.rsi != null ? t.rsi.toFixed(1) : '—') + '</span>',
      '<span class="opt-tech-pill ' + rsiSt.cls + '">' + rsiSt.label + '</span>',
      escapeHtml(rsiSt.note),
      TIPS.rsi
    );

    if (t.macd){
      var macdVal = '<span class="opt-tech-num">' + (t.macd.hist >= 0 ? '+' : '') + t.macd.hist.toFixed(3) + '</span>' +
        '<span class="opt-tech-vsub">line ' + t.macd.line.toFixed(3) + ' · signal ' + t.macd.signal.toFixed(3) + '</span>';
      html += techCard(
        'MACD (12,26,9)',
        macdVal,
        '<span class="opt-tech-pill ' + macdSt.cls + '">' + macdSt.label + '</span>',
        escapeHtml(macdSt.note),
        TIPS.macd
      );
    } else {
      html += techCard('MACD (12,26,9)', '<span class="opt-tech-num">—</span>', '', 'not enough history', TIPS.macd);
    }

    if (t.sr){
      var sup = t.sr.s20;
      var supFar = t.sr.s50;
      var supVal = '<span class="opt-tech-num">' + (sup != null ? '$' + fmt(sup) : '—') + '</span>' +
        (supFar != null && supFar !== sup ? '<span class="opt-tech-vsub">50d $' + fmt(supFar) + '</span>' : '');
      var supDist = sup != null ? fmtDistance(sup, spot) : '';
      var supBroken = (sup != null && spot < sup);
      html += techCard(
        'Support (20d)',
        supVal,
        supDist ? '<span class="opt-tech-pill ' + (supBroken ? 'warn' : 'fair') + '">' + supDist + '</span>' : '',
        supBroken
          ? 'Spot is below the 20-day low — buyers haven\'t defended this level yet'
          : 'Recent floor — buyers stepped in here; a break below is a meaningful technical event',
        TIPS.support
      );

      var res = t.sr.r20;
      var resFar = t.sr.r50;
      var resVal = '<span class="opt-tech-num">' + (res != null ? '$' + fmt(res) : '—') + '</span>' +
        (resFar != null && resFar !== res ? '<span class="opt-tech-vsub">50d $' + fmt(resFar) + '</span>' : '');
      var resDist = res != null ? fmtDistance(res, spot) : '';
      var resBroken = (res != null && spot > res);
      html += techCard(
        'Resistance (20d)',
        resVal,
        resDist ? '<span class="opt-tech-pill ' + (resBroken ? 'pos' : 'fair') + '">' + resDist + '</span>' : '',
        resBroken
          ? 'Spot is above the 20-day high — fresh breakout; watch for follow-through'
          : 'Recent ceiling — sellers showed up here; a clean break above is a meaningful technical event',
        TIPS.resistance
      );
    }

    grid.innerHTML = html;
    box.hidden = false;
  }

  // --- Fundamentals + earnings -------------------------------------------
  function fmtBigDollars(n){
    if (n == null || !isFinite(n)) return null;
    var a = Math.abs(n);
    if (a >= 1e12) return '$' + (n/1e12).toFixed(2) + 'T';
    if (a >= 1e9) return '$' + (n/1e9).toFixed(2) + 'B';
    if (a >= 1e6) return '$' + (n/1e6).toFixed(2) + 'M';
    return '$' + Math.round(n).toLocaleString();
  }
  function fundMetric(label, value, tone){
    if (value == null || value === '') return '';
    var toneCls = tone ? ' tone-' + tone : '';
    return '<div class="opt-fund-metric' + toneCls + '">' +
      '<div class="opt-fund-metric-label">' + escapeHtml(label) + '</div>' +
      '<div class="opt-fund-metric-value">' + value + '</div>' +
    '</div>';
  }
  function fundVerdictLabel(v){
    if (v === 'strong') return 'Strong fundamentals';
    if (v === 'weak') return 'Weak fundamentals';
    return 'Mixed fundamentals';
  }
  function renderFundamentals(sym){
    var box = $('opt-fundamentals');
    if (!box) return;
    var f = state.fundamentals;
    if (!f){ box.hidden = true; return; }
    var hasJudgment = f.judgment && (f.judgment.positives && f.judgment.positives.length || f.judgment.negatives && f.judgment.negatives.length || f.judgment.summary);
    var hasMetrics = (f.trailingPE != null || f.forwardPE != null || f.marketCap != null || f.profitMargin != null || f.revenueGrowthYoy != null || f.lastQuarter || f.nextEarningsDate);
    if (!hasJudgment && !hasMetrics){ box.hidden = true; return; }

    var verdictEl = $('opt-fund-verdict');
    var summaryEl = $('opt-fund-summary');
    var recapEl = $('opt-fund-recap');
    var posList = $('opt-fund-pos-list');
    var negList = $('opt-fund-neg-list');
    var metricsEl = $('opt-fund-metrics');

    if (hasJudgment){
      var j = f.judgment;
      var v = j.verdict || 'mixed';
      verdictEl.className = 'opt-fund-verdict ' + v;
      verdictEl.textContent = fundVerdictLabel(v);
      summaryEl.textContent = j.summary || '';
      summaryEl.hidden = !j.summary;
      if (j.earningsRecap){
        recapEl.innerHTML = '<span class="opt-fund-recap-label">Last earnings</span> ' + escapeHtml(j.earningsRecap);
        recapEl.hidden = false;
      } else {
        recapEl.hidden = true;
        recapEl.innerHTML = '';
      }
      posList.innerHTML = (j.positives || []).map(function(p){
        return '<li>' + escapeHtml(p) + '</li>';
      }).join('') || '<li class="opt-fund-empty">No clear positives surfaced.</li>';
      negList.innerHTML = (j.negatives || []).map(function(p){
        return '<li>' + escapeHtml(p) + '</li>';
      }).join('') || '<li class="opt-fund-empty">No clear negatives surfaced.</li>';
    } else {
      verdictEl.className = 'opt-fund-verdict';
      verdictEl.textContent = '';
      summaryEl.textContent = 'AI judgment unavailable for this ticker — raw metrics below.';
      summaryEl.hidden = false;
      recapEl.hidden = true;
      recapEl.innerHTML = '';
      posList.innerHTML = '';
      negList.innerHTML = '';
    }

    var metrics = '';
    metrics += fundMetric('Market cap', fmtBigDollars(f.marketCap));
    metrics += fundMetric('Trailing P/E', f.trailingPE != null ? f.trailingPE.toFixed(1) : null);
    metrics += fundMetric('Forward P/E', f.forwardPE != null ? f.forwardPE.toFixed(1) : null);
    metrics += fundMetric('PEG', f.pegRatio != null ? f.pegRatio.toFixed(2) : null);
    metrics += fundMetric('Price / Sales', f.priceToSales != null ? f.priceToSales.toFixed(2) : null);
    metrics += fundMetric('Rev. growth YoY', f.revenueGrowthYoy != null ? f.revenueGrowthYoy.toFixed(1) + '%' : null,
      f.revenueGrowthYoy != null ? (f.revenueGrowthYoy > 0 ? 'pos' : 'neg') : null);
    metrics += fundMetric('EPS growth YoY', f.earningsGrowthYoy != null ? f.earningsGrowthYoy.toFixed(1) + '%' : null,
      f.earningsGrowthYoy != null ? (f.earningsGrowthYoy > 0 ? 'pos' : 'neg') : null);
    metrics += fundMetric('Profit margin', f.profitMargin != null ? f.profitMargin.toFixed(1) + '%' : null,
      f.profitMargin != null ? (f.profitMargin > 10 ? 'pos' : f.profitMargin < 0 ? 'neg' : null) : null);
    metrics += fundMetric('Operating margin', f.operatingMargin != null ? f.operatingMargin.toFixed(1) + '%' : null);
    metrics += fundMetric('ROE', f.returnOnEquity != null ? f.returnOnEquity.toFixed(1) + '%' : null,
      f.returnOnEquity != null ? (f.returnOnEquity > 15 ? 'pos' : f.returnOnEquity < 0 ? 'neg' : null) : null);
    metrics += fundMetric('Debt / Equity', f.debtToEquity != null ? f.debtToEquity.toFixed(0) : null,
      f.debtToEquity != null ? (f.debtToEquity > 200 ? 'neg' : null) : null);
    metrics += fundMetric('Free cash flow', fmtBigDollars(f.freeCashFlow),
      f.freeCashFlow != null ? (f.freeCashFlow > 0 ? 'pos' : 'neg') : null);
    metrics += fundMetric('Dividend yield', f.dividendYield != null && f.dividendYield > 0 ? f.dividendYield.toFixed(2) + '%' : null);
    if (f.lastQuarter){
      var lq = f.lastQuarter;
      var surprise = lq.surprisePct != null ? ((lq.surprisePct >= 0 ? '+' : '') + lq.surprisePct.toFixed(1) + '%') : null;
      var beatTone = lq.surprisePct == null ? null : (lq.surprisePct > 2 ? 'pos' : lq.surprisePct < -2 ? 'neg' : null);
      var lqVal = 'EPS ' + (lq.epsActual != null ? lq.epsActual.toFixed(2) : '—');
      if (lq.epsEstimate != null) lqVal += ' <span class="opt-fund-metric-sub">est ' + lq.epsEstimate.toFixed(2) + '</span>';
      if (surprise) lqVal += ' <span class="opt-fund-metric-sub">(' + surprise + ')</span>';
      var lqLabel = 'Last earnings' + (lq.period ? ' (' + lq.period + ')' : '') + (lq.date ? ' · ' + lq.date : '');
      metrics += fundMetric(lqLabel, lqVal, beatTone);
    }
    if (f.nextEarningsDate){
      metrics += fundMetric('Next earnings', f.nextEarningsDate, 'warn');
    }
    if (f.targetMeanPrice != null && state.spot){
      var upside = (f.targetMeanPrice - state.spot) / state.spot * 100;
      var upsideStr = (upside >= 0 ? '+' : '') + upside.toFixed(1) + '%';
      metrics += fundMetric('Analyst target',
        '$' + f.targetMeanPrice.toFixed(2) + ' <span class="opt-fund-metric-sub">' + upsideStr + ' vs spot</span>',
        upside > 5 ? 'pos' : upside < -5 ? 'neg' : null);
    }
    if (f.recommendationKey){
      var recPretty = f.recommendationKey.replace(/_/g, ' ');
      var recTone = /buy|outperform/i.test(f.recommendationKey) ? 'pos' : /sell|underperform/i.test(f.recommendationKey) ? 'neg' : null;
      metrics += fundMetric('Consensus', recPretty + (f.numberOfAnalystOpinions ? ' <span class="opt-fund-metric-sub">' + f.numberOfAnalystOpinions + ' analysts</span>' : ''), recTone);
    }
    metricsEl.innerHTML = metrics;
    box.hidden = false;
  }

  function onExpiryChange(){
    var exp = Number($('opt-expiry').value);
    state.currentExp = exp;
    populateStrikes();
    renderMaxPain();
    scheduleEvaluate();
    // The baked chain for the new expiration is already cached, but during
    // market hours the user wants fresh quotes for the expiration they're
    // looking at — fire one extra poll immediately and let the interval
    // pick up from there.
    if (currentMarketState() === 'REGULAR') refreshLiveChain(state.symbol, exp);
  }

  // --- Narratives ---------------------------------------------------------
  function tickerChipHtml(sym, side){
    var sec = SECTORS[sym] || '';
    var titleAttr = sec ? ' title="' + escapeHtml(sec) + '"' : '';
    return '<span class="narr-chip ' + side + '"' + titleAttr + '>' + escapeHtml(sym) + '</span>';
  }
  function narrLifeLabel(n){
    var d = n.daysRunning | 0;
    if (!d || d <= 1) return 'New today';
    return 'Day ' + d;
  }
  function narrStatusLabel(s){
    return ({ active:'Active', building:'Building', fading:'Fading' })[s] || 'Active';
  }
  function narrTimeframeLabel(tf){
    return ({ immediate:'This week', 'near-term':'1-4 wks', 'medium-term':'1-3 mo', 'long-term':'3+ mo' })[tf] || 'Near-term';
  }
  function strengthBarHtml(strength){
    var s = Math.max(0, Math.min(100, strength | 0));
    var tier = s >= 75 ? 'hi' : s >= 45 ? 'mid' : 'lo';
    return '<div class="narr-strength" title="Strength ' + s + ' / 100">' +
      '<div class="narr-strength-track"><div class="narr-strength-fill ' + tier + '" style="width:' + s + '%"></div></div>' +
      '<span class="narr-strength-num">' + s + '</span>' +
    '</div>';
  }
  function triggersHtml(n){
    if (!n.triggers || !n.triggers.length) return '';
    var label = n.status === 'building' ? 'Needs trigger' : (n.status === 'fading' ? 'Watch for reset' : 'Triggers to watch');
    return '<div class="narr-triggers">' +
      '<span class="narr-triggers-label">' + escapeHtml(label) + '</span>' +
      '<ul class="narr-triggers-list">' +
      n.triggers.map(function(t){ return '<li>' + escapeHtml(t) + '</li>'; }).join('') +
      '</ul>' +
    '</div>';
  }
  function conflictsHtml(n){
    if (!n.conflictsWith || !n.conflictsWith.length) return '';
    return '<div class="narr-conflicts">' +
      '<span class="narr-conflicts-label">Clashes with</span>' +
      n.conflictsWith.map(function(c){ return '<span class="narr-conflict-chip">' + escapeHtml(c) + '</span>'; }).join('') +
    '</div>';
  }
  function renderNarratives(){
    var list = $('narratives-list');
    var empty = $('narratives-empty');
    var ended = $('narratives-ended');
    var count = $('narratives-count');
    if (!list) return;
    if (count){
      if (NARRATIVES.length){
        var activeN = 0, buildingN = 0;
        for (var i=0; i<NARRATIVES.length; i++){
          if (NARRATIVES[i].status === 'building') buildingN++;
          else if (NARRATIVES[i].status !== 'fading') activeN++;
        }
        var parts = [activeN + ' active'];
        if (buildingN) parts.push(buildingN + ' building');
        count.textContent = parts.join(' · ');
      } else {
        count.textContent = '';
      }
    }
    if (!NARRATIVES.length){
      list.innerHTML = '';
      if (empty) empty.hidden = false;
    } else {
      if (empty) empty.hidden = true;
      list.innerHTML = NARRATIVES.map(function(n, idx){
        var sent = n.sentiment === 'bearish' ? 'bearish' : 'bullish';
        var status = ['active','building','fading'].indexOf(n.status) >= 0 ? n.status : 'active';
        var tf = n.timeframe || 'near-term';
        var confLabel = ({ high:'High', medium:'Medium', low:'Low' })[n.confidence] || 'Medium';
        var longChips = (n.longs || []).map(function(t){ return tickerChipHtml(t, 'long'); }).join('');
        var shortChips = (n.shorts || []).map(function(t){ return tickerChipHtml(t, 'short'); }).join('');
        var longRow = longChips ? '<div class="narr-side-row long"><span class="narr-side-label">Long</span>' + longChips + '</div>' : '';
        var shortRow = shortChips ? '<div class="narr-side-row short"><span class="narr-side-label">Short</span>' + shortChips + '</div>' : '';
        var rankLabel = (idx + 1) + ' / ' + NARRATIVES.length;
        return '<article class="narr" data-sent="' + sent + '" data-status="' + status + '" role="listitem">' +
          '<span class="narr-accent" aria-hidden="true"></span>' +
          '<header class="narr-head">' +
            '<span class="narr-rank" aria-label="Rank">#' + (idx + 1) + '</span>' +
            '<h3 class="narr-name">' + escapeHtml(n.name) + '</h3>' +
            '<span class="narr-tag sent ' + sent + '">' + (sent === 'bullish' ? 'Bullish' : 'Bearish') + '</span>' +
            '<span class="narr-tag status ' + status + '">' + narrStatusLabel(status) + '</span>' +
            '<span class="narr-tag tf" title="Typical playout window">' + narrTimeframeLabel(tf) + '</span>' +
            '<span class="narr-tag conf" title="' + rankLabel + '">Conf · ' + confLabel + '</span>' +
            '<span class="narr-life"><span class="narr-life-dot"></span>' + escapeHtml(narrLifeLabel(n)) + '</span>' +
          '</header>' +
          strengthBarHtml(n.strength) +
          '<p class="narr-thesis">' + escapeHtml(n.thesis || '') + '</p>' +
          longRow + shortRow +
          triggersHtml(n) +
          conflictsHtml(n) +
        '</article>';
      }).join('');
    }
    if (ended){
      if (RECENTLY_ENDED.length){
        ended.innerHTML = '<div class="narr-ended-head">Recently cooled off</div>' +
          '<div class="narr-ended-strip">' +
          RECENTLY_ENDED.map(function(e){
            var d = e.daysSince | 0;
            var ran = e.ranDays | 0;
            var ago = d === 1 ? 'yesterday' : d + ' days ago';
            var run = ran <= 1 ? 'one-day blip' : ran + '-day run';
            return '<div class="narr-ended-card">' +
              '<div class="narr-ended-name">' + escapeHtml(e.name) + '</div>' +
              '<div class="narr-ended-meta">' + ago + ' · ' + run + '</div>' +
            '</div>';
          }).join('') +
          '</div>';
      } else {
        ended.innerHTML = '';
      }
    }
    var macro = $('narratives-macro');
    if (macro){
      if (MACRO_HEADLINES.length){
        // Show the top 8 freshest macro hits so users can see what the
        // narrative engine just looked at. Collapsed by default — it's
        // context, not the headline UI.
        macro.innerHTML = '<details class="narr-macro-details">' +
          '<summary><span class="narr-macro-head">Macro signal feed</span>' +
          '<span class="narr-macro-meta">' + MACRO_HEADLINES.length + ' headlines · Fed · BLS · Treasury · SEC · MarketWatch · CNBC</span></summary>' +
          '<ul class="narr-macro-list">' +
          MACRO_HEADLINES.slice(0, 12).map(function(h){
            var date = h.publishedAt ? h.publishedAt.slice(0, 10) : '';
            return '<li>' +
              (date ? '<span class="narr-macro-date">' + escapeHtml(date) + '</span>' : '') +
              '<span class="narr-macro-pub">' + escapeHtml(h.publisher || 'source') + '</span>' +
              '<span class="narr-macro-title">' + escapeHtml(h.title || '') + '</span>' +
            '</li>';
          }).join('') +
          '</ul></details>';
      } else {
        macro.innerHTML = '';
      }
    }
  }
  function narrativesForTicker(sym){
    if (!sym) return [];
    var hits = [];
    for (var i=0; i<NARRATIVES.length; i++){
      var n = NARRATIVES[i];
      if ((n.longs || []).indexOf(sym) >= 0) hits.push({ n: n, side: 'long' });
      else if ((n.shorts || []).indexOf(sym) >= 0) hits.push({ n: n, side: 'short' });
    }
    return hits;
  }
  function renderTickerNarrativeChips(sym){
    var box = $('opt-narr-chips');
    if (!box) return;
    var hits = narrativesForTicker(sym);
    if (!hits.length){ box.hidden = true; box.innerHTML = ''; return; }
    box.hidden = false;
    box.innerHTML = '<span class="opt-narr-chips-label">Narratives</span>' + hits.map(function(h){
      var sentLabel = h.n.sentiment === 'bearish' ? 'Bearish' : 'Bullish';
      return '<span class="opt-narr-chip ' + h.side + '" title="' + escapeHtml(h.n.thesis || '') + '">' +
        escapeHtml(h.n.name) +
        '<span class="opt-narr-chip-side">' + h.side.toUpperCase() + ' · ' + sentLabel + '</span>' +
      '</span>';
    }).join('');
  }

  // --- Bind ---------------------------------------------------------------
  function bind(){
    renderFreshness();
    bindThemeToggle();
    bindTabs();
    combo.init();
    renderNarratives();

    var radioGroup = document.querySelector('[role="radiogroup"]');
    if (radioGroup){
      radioGroup.addEventListener('change', function(ev){
        if (ev.target && ev.target.name === 'opt-type'){
          if (state.currentExp) populateStrikes();
          scheduleEvaluate();
        }
      });
    }
    var expSel = $('opt-expiry');
    if (expSel) expSel.addEventListener('change', onExpiryChange);
    var strikeSel = $('opt-strike');
    if (strikeSel) strikeSel.addEventListener('change', scheduleEvaluate);

    var manualForm = $('opt-manual-form');
    if (manualForm){
      manualForm.addEventListener('submit', evaluateManual);
      var paste = $('m-paste');
      if (paste) paste.addEventListener('input', onPasteContract);
      var chainSection = $('opt-eval-section');
      if (chainSection){
        chainSection.addEventListener('click', function(ev){
          var btn = ev.target.closest && ev.target.closest('.opt-tweak-btn');
          if (!btn) return;
          tweakInManual(btn.getAttribute('data-tweak'));
        });
      }
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bind);
  else bind();
})();
