// Generated by scripts/build.mjs — do not edit by hand.
(function(){
  // Theme bootstrap. Runs synchronously before the rest of the IIFE binds
  // so we never flash the wrong theme. Respects an explicit saved
  // preference, otherwise mirrors prefers-color-scheme.
  try {
    var saved = localStorage.getItem('stonks-theme');
    var sys = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', saved || sys);
  } catch (_) {
    document.documentElement.setAttribute('data-theme', 'light');
  }

  var MANIFEST = window.STONKS_MANIFEST || { symbols: [], narratives: [], recentlyEnded: [], sectors: {}, spots: {} };
  var SYMBOLS = Array.isArray(MANIFEST.symbols) ? MANIFEST.symbols : [];
  var NARRATIVES = Array.isArray(MANIFEST.narratives) ? MANIFEST.narratives : [];
  var RECENTLY_ENDED = Array.isArray(MANIFEST.recentlyEnded) ? MANIFEST.recentlyEnded : [];
  var SECTORS = MANIFEST.sectors || {};
  var SPOTS = MANIFEST.spots || {};
  var RFR = 0.045;
  var CHAIN_CACHE = Object.create(null);
  var state = { symbol: null, spot: null, expirations: [], chains: {}, currentExp: null, news: null };
  var evalTimer = null;
  var stickyIO = null;

  function $(id){ return document.getElementById(id); }
  function setStatus(elemId, msg, kind){
    var el = $(elemId); if (!el) return;
    el.textContent = msg || '';
    el.className = 'opt-status' + (kind ? ' ' + kind : '');
  }
  function fmt(n, d){ if (n == null || !isFinite(n)) return '—'; return Number(n).toFixed(d == null ? 2 : d); }
  function fmtPct(n){ if (n == null || !isFinite(n)) return '—'; return n.toFixed(2) + '%'; }
  function fmtMoney(n){ if (n == null || !isFinite(n)) return '—'; return '$' + Number(n).toLocaleString(undefined, {minimumFractionDigits:2, maximumFractionDigits:2}); }
  function escapeHtml(s){
    return String(s).replace(/[&<>"']/g, function(ch){
      return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch];
    });
  }
  function debounce(fn, ms){
    return function(){
      var args = arguments;
      clearTimeout(evalTimer);
      evalTimer = setTimeout(function(){ fn.apply(null, args); }, ms);
    };
  }

  // --- Freshness banner ---------------------------------------------------
  function renderFreshness(){
    var banner = $('freshness-banner');
    var bannerText = $('freshness-text');
    if (!banner || !bannerText) return;
    var iso = banner.getAttribute('data-built-at');
    var built = iso ? new Date(iso) : null;
    if (!built || isNaN(built.getTime())) return;
    var ageH = (Date.now() - built.getTime()) / 3600000;
    function rel(h){
      if (h < 1) { var m = Math.max(1, Math.round(h*60)); return m + ' minute' + (m===1?'':'s') + ' ago'; }
      if (h < 36) { var hh = Math.round(h); return hh + ' hour' + (hh===1?'':'s') + ' ago'; }
      var d = Math.round(h/24); return d + ' day' + (d===1?'':'s') + ' ago';
    }
    var dateLabel = built.toLocaleDateString('en-US', { weekday:'short', month:'short', day:'numeric', timeZone:'America/New_York' });
    banner.classList.remove('warn','bad');
    if (ageH > 24*7) {
      banner.classList.add('bad');
      bannerText.innerHTML = 'Very stale — last refreshed ' + dateLabel + '. <span class="freshness-detail">Verify quotes on your broker before trading.</span>';
    } else if (ageH > 36) {
      banner.classList.add('warn');
      bannerText.innerHTML = 'Stale data — last refreshed ' + dateLabel + '. <span class="freshness-detail">Verify quotes on your broker before trading.</span>';
    } else {
      bannerText.innerHTML = 'Refreshed ' + rel(ageH) + ' <span class="freshness-detail">· end-of-session quotes from Yahoo</span>';
    }
  }

  // --- Math: Black-Scholes ------------------------------------------------
  function npdf(x){ return Math.exp(-0.5*x*x) / Math.sqrt(2*Math.PI); }
  function ncdf(x){
    var b1=0.319381530, b2=-0.356563782, b3=1.781477937, b4=-1.821255978, b5=1.330274429;
    var a = Math.abs(x), t = 1/(1 + 0.2316419*a);
    var poly = ((((b5*t + b4)*t + b3)*t + b2)*t + b1) * t;
    var p = 1 - npdf(a)*poly;
    return x < 0 ? 1-p : p;
  }
  function greeks(type, S, K, T, sigma, r){
    if (!(S>0 && K>0 && T>0 && sigma>0)) return null;
    var sqrtT = Math.sqrt(T);
    var d1 = (Math.log(S/K) + (r + 0.5*sigma*sigma)*T) / (sigma*sqrtT);
    var d2 = d1 - sigma*sqrtT;
    var delta = type === 'call' ? ncdf(d1) : ncdf(d1) - 1;
    var thetaYr = type === 'call'
      ? -S*npdf(d1)*sigma/(2*sqrtT) - r*K*Math.exp(-r*T)*ncdf(d2)
      : -S*npdf(d1)*sigma/(2*sqrtT) + r*K*Math.exp(-r*T)*ncdf(-d2);
    var gamma = npdf(d1) / (S*sigma*sqrtT);
    var vega = S*npdf(d1)*sqrtT / 100;
    return { delta: delta, thetaDay: thetaYr/365, gamma: gamma, vega: vega };
  }

  // --- Input parsing ------------------------------------------------------
  function parseLoose(raw){
    if (raw == null) return NaN;
    var s = String(raw).trim();
    if (!s) return NaN;
    s = s.split(/[x×]/i)[0];
    s = s.replace(/[\$,%\s\u00a0]/g, '');
    return parseFloat(s);
  }
  function parseOCC(raw){
    if (raw == null) return null;
    var s = String(raw).trim().toUpperCase();
    var m = s.match(/^([A-Z][A-Z0-9.]{0,5})(\d{2})(\d{2})(\d{2})([CP])(\d{8})$/);
    if (!m) return null;
    var yy = parseInt(m[2],10), mm = parseInt(m[3],10), dd = parseInt(m[4],10);
    if (mm<1||mm>12||dd<1||dd>31) return null;
    var year = 2000 + yy;
    var iso = year + '-' + (mm<10?'0':'') + mm + '-' + (dd<10?'0':'') + dd;
    return { root: m[1], type: m[5]==='C' ? 'call' : 'put', strike: parseInt(m[6],10)/1000, expiryISO: iso };
  }

  // --- Theme toggle -------------------------------------------------------
  function bindThemeToggle(){
    var btn = $('theme-toggle'); if (!btn) return;
    btn.addEventListener('click', function(){
      var current = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
      var next = current === 'dark' ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', next);
      try { localStorage.setItem('stonks-theme', next); } catch (_) {}
    });
  }

  // --- Combobox ----------------------------------------------------------
  var combo = {
    input: null, listbox: null, items: [], activeIdx: -1, open: false,
    init: function(){
      this.input = $('symbol-input');
      this.listbox = $('symbol-listbox');
      if (!this.input || !this.listbox) return;
      var self = this;
      this.input.addEventListener('input', function(){ self.filter(); });
      this.input.addEventListener('focus', function(){ self.filter(); });
      this.input.addEventListener('keydown', function(e){ self.onKey(e); });
      this.input.addEventListener('blur', function(){ setTimeout(function(){ self.close(); }, 120); });
      var clear = $('symbol-clear');
      if (clear) clear.addEventListener('mousedown', function(e){
        e.preventDefault(); self.input.value = ''; self.input.focus(); self.filter();
      });
      this.listbox.addEventListener('mousedown', function(e){
        var li = e.target.closest && e.target.closest('li[data-sym]');
        if (!li) return;
        e.preventDefault();
        self.commit(li.getAttribute('data-sym'));
      });
    },
    rank: function(q){
      q = (q||'').trim().toUpperCase();
      if (!q) return SYMBOLS.slice(0, 50);
      var prefix = [], contains = [], sector = [];
      for (var i=0; i<SYMBOLS.length; i++){
        var sym = SYMBOLS[i];
        var sec = (SECTORS[sym] || '').toUpperCase();
        if (sym.indexOf(q) === 0) prefix.push(sym);
        else if (sym.indexOf(q) >= 0) contains.push(sym);
        else if (sec.indexOf(q) >= 0) sector.push(sym);
      }
      return prefix.concat(contains, sector).slice(0, 50);
    },
    filter: function(){
      var matches = this.rank(this.input.value);
      this.items = matches;
      if (!matches.length){
        this.listbox.innerHTML = '<li class="combo-empty">No matches</li>';
      } else {
        var html = '';
        for (var i=0; i<matches.length; i++){
          var sym = matches[i];
          var sec = SECTORS[sym] || '';
          var spot = SPOTS[sym];
          html += '<li role="option" data-sym="' + sym + '" id="combo-opt-' + sym + '">' +
            '<span class="combo-sym">' + sym + '</span>' +
            '<span class="combo-spot">' + (spot != null ? fmtMoney(spot) : '') + '</span>' +
            '<span class="combo-sector">' + escapeHtml(sec) + '</span>' +
          '</li>';
        }
        this.listbox.innerHTML = html;
      }
      this.activeIdx = -1;
      this.show();
    },
    show: function(){
      this.listbox.hidden = false;
      this.input.setAttribute('aria-expanded', 'true');
      this.open = true;
    },
    close: function(){
      this.listbox.hidden = true;
      this.input.setAttribute('aria-expanded', 'false');
      this.input.removeAttribute('aria-activedescendant');
      this.open = false;
      this.activeIdx = -1;
    },
    move: function(delta){
      if (!this.items.length) return;
      this.activeIdx = (this.activeIdx + delta + this.items.length) % this.items.length;
      var nodes = this.listbox.querySelectorAll('li[data-sym]');
      for (var i=0; i<nodes.length; i++) nodes[i].classList.toggle('is-active', i === this.activeIdx);
      var sym = this.items[this.activeIdx];
      this.input.setAttribute('aria-activedescendant', 'combo-opt-' + sym);
      var active = nodes[this.activeIdx];
      if (active && active.scrollIntoView) active.scrollIntoView({ block: 'nearest' });
    },
    onKey: function(e){
      if (e.key === 'ArrowDown'){ e.preventDefault(); if (!this.open) this.filter(); else this.move(1); }
      else if (e.key === 'ArrowUp'){ e.preventDefault(); this.move(-1); }
      else if (e.key === 'Enter'){
        if (this.activeIdx >= 0){ e.preventDefault(); this.commit(this.items[this.activeIdx]); }
        else if (this.items.length === 1){ e.preventDefault(); this.commit(this.items[0]); }
      }
      else if (e.key === 'Escape'){ this.close(); }
    },
    commit: function(sym){
      if (!sym) return;
      this.input.value = sym;
      this.close();
      state.symbol = sym;
      loadChain();
    }
  };

  // --- Chain controls -----------------------------------------------------
  function fmtExpiryLabel(epoch){
    var d = new Date(epoch*1000);
    return d.toLocaleDateString('en-US', { year:'numeric', month:'short', day:'numeric', timeZone:'America/New_York' });
  }
  function getOptType(){
    var r = document.querySelector('input[name="opt-type"]:checked');
    return r ? r.value : 'call';
  }
  function populateExpiry(){
    var sel = $('opt-expiry'); sel.innerHTML = '';
    state.expirations.forEach(function(epoch){
      var o = document.createElement('option');
      o.value = epoch; o.textContent = fmtExpiryLabel(epoch);
      sel.appendChild(o);
    });
  }
  function populateStrikes(){
    var type = getOptType();
    var chain = state.chains[state.currentExp];
    var sel = $('opt-strike');
    if (!chain){ sel.innerHTML = ''; return; }
    var rows = (type === 'call' ? chain.c : chain.p) || [];
    if (!rows.length){
      sel.innerHTML = '<option disabled>No ' + type + 's available</option>';
      return;
    }
    var spot = state.spot;
    var bestIdx = 0, bestDist = Infinity;
    var parts = new Array(rows.length);
    for (var i=0; i<rows.length; i++){
      var r = rows[i];
      var d = Math.abs((r.s||0) - spot);
      if (d < bestDist){ bestDist = d; bestIdx = i; }
      parts[i] = '<option value="' + i + '">$' + fmt(r.s) + ' · bid ' + fmt(r.b) + ' / ask ' + fmt(r.a) + '</option>';
    }
    sel.innerHTML = parts.join('');
    sel.selectedIndex = bestIdx;
  }
  function findContract(){
    var type = getOptType();
    var chain = state.chains[state.currentExp]; if (!chain) return null;
    var rows = (type === 'call' ? chain.c : chain.p) || [];
    var idx = Number($('opt-strike').value);
    if (!isFinite(idx)) return null;
    return rows[idx] || null;
  }

  // --- Grading ------------------------------------------------------------
  function gradeSpread(spreadPct){
    if (spreadPct <= 5)  return { label:'Tight',    cls:'good', note:'narrow spread — easy fills' };
    if (spreadPct <= 15) return { label:'Moderate', cls:'fair', note:'spread is workable but costs you on entry/exit' };
    return { label:'Wide', cls:'bad', note:'wide spread — illiquid, expect slippage' };
  }
  function gradeDelta(delta){
    var a = Math.abs(delta);
    if (a >= 0.40 && a <= 0.70) return { label:'Balanced',     cls:'good', note:'good directional sensitivity without paying full intrinsic' };
    if (a >= 0.30 && a < 0.40)  return { label:'Slightly OTM', cls:'fair', note:'cheaper but needs a real move to pay' };
    if (a > 0.70)               return { label:'Deep ITM',     cls:'fair', note:'moves nearly 1:1 with the stock — limited leverage' };
    return { label:'Far OTM', cls:'bad', note:'lottery ticket — most likely expires worthless' };
  }
  function gradeTheta(thetaDay, mid){
    if (mid <= 0 || thetaDay == null) return { label:'—', cls:'fair', note:'theta unavailable' };
    var bleed = Math.abs(thetaDay) / mid * 100;
    if (bleed < 1) return { label:'Slow decay',   cls:'good', note:'~' + bleed.toFixed(2) + '% / day — plenty of runway' };
    if (bleed < 3) return { label:'Normal decay', cls:'fair', note:'~' + bleed.toFixed(2) + '% / day — standard time pressure' };
    return { label:'Bleeding', cls:'bad', note:'~' + bleed.toFixed(2) + '% / day — heavy time decay' };
  }
  function overallVerdict(grades){
    var bad = grades.filter(function(g){ return g.cls === 'bad'; }).length;
    var good = grades.filter(function(g){ return g.cls === 'good'; }).length;
    if (bad >= 2) return { label:'Poor contract', cls:'bad' };
    if (bad === 1) return { label:'Mixed — proceed with caution', cls:'fair' };
    if (good >= 2) return { label:'Good contract', cls:'good' };
    return { label:'Acceptable', cls:'fair' };
  }
  function applyNewsNudge(verdict, news){
    if (!news || !news.sentiment) return verdict;
    if (verdict.cls !== 'fair') return verdict;
    if (news.sentiment === 'bullish') return { label:'Good contract · news tailwind', cls:'good', nudged:true };
    if (news.sentiment === 'bearish') return { label:'Poor contract · news headwind', cls:'bad', nudged:true };
    return verdict;
  }

  var TIPS = {
    spread: 'Gap between bid (what buyers pay) and ask (what sellers want). Wider = you lose more on entry/exit.',
    delta:  'How much the option moves per $1 the stock moves. ~0.50 = at-the-money, ~1.00 = deep ITM, near 0 = far OTM lottery.',
    theta:  'Daily $ the contract loses just from time passing. Higher = the clock is running against you faster.',
    iv:     'Implied volatility — the market\'s guess at how much the stock will move. High IV = expensive premium.',
    gamma:  'How fast delta changes as the stock moves. Higher near ATM and near expiry.',
    vega:   'How much the contract gains/loses per 1 point change in implied volatility.'
  };
  function tipChip(text){
    if (!text) return '';
    var t = text.replace(/"/g, '&quot;');
    return ' <span class="tip" tabindex="0" role="button" aria-label="Explain: ' + t + '" data-tip="' + t + '">?</span>';
  }
  function row(label, value, sub, tip){
    return '<div class="opt-row"><div class="opt-row-label">' + label + tipChip(tip) +
      '</div><div class="opt-row-value">' + value + (sub ? ' <span class="opt-row-sub">' + sub + '</span>' : '') + '</div></div>';
  }
  function gradeChip(g){ return '<span class="opt-grade ' + g.cls + '">' + g.label + '</span>'; }
  function verdictExplainer(cls){
    var msg;
    if (cls === 'good') msg = 'Clean contract. Spread is tight, delta is balanced, theta is manageable. Direction and sizing are up to you.';
    else if (cls === 'bad') msg = 'Skip or rework. Wide spread or far-OTM delta or heavy theta will eat your edge before the trade plays out. Look for a tighter strike, a more liquid expiry, or a different ticker.';
    else msg = 'Workable but not ideal. Read the chip notes below — usually one of spread, delta, or theta is asking you to compromise. Decide whether that trade-off is worth it.';
    return '<div class="opt-explain ' + cls + '"><b>What this means:</b> ' + msg + '</div>';
  }
  function newsTakeHtml(news, ticker, nudged){
    if (!news || !news.paragraph) return '';
    var sentimentLabel = ({ bullish:'Bullish', neutral:'Neutral', bearish:'Bearish', uncertain:'Uncertain' })[news.sentiment] || 'Neutral';
    var heading = 'AI news take' + (ticker ? (' · ' + escapeHtml(ticker)) : '') + ' · ' + sentimentLabel;
    var note = nudged ? '<div class="opt-news-note">This news context shifted the verdict above from <b>Acceptable</b>.</div>' : '';
    return '<div class="opt-news ' + (news.sentiment || 'neutral') + '">' +
      '<div class="opt-news-head">' + heading + '</div>' +
      '<div class="opt-news-body">' + escapeHtml(news.paragraph) + '</div>' +
      note +
    '</div>';
  }

  function buildResultHtml(input){
    var bid = input.bid, ask = input.ask;
    var mid = (bid != null && ask != null && (bid + ask) > 0) ? (bid + ask) / 2 : (input.last || null);
    var spread = (bid != null && ask != null) ? (ask - bid) : null;
    var spreadPct = (spread != null && mid > 0) ? (spread/mid * 100) : null;
    var iv = input.iv;
    var T = (input.expEpoch*1000 - Date.now()) / (365*24*3600*1000);
    var g = (T > 0 && iv > 0 && input.spot > 0 && input.strike > 0)
      ? greeks(input.type, input.spot, input.strike, T, iv, RFR) : null;

    var sGrade = spreadPct != null ? gradeSpread(spreadPct) : { label:'—', cls:'fair', note:'no quote' };
    var dGrade = g ? gradeDelta(g.delta) : { label:'—', cls:'fair', note:'delta unavailable — IV missing' };
    var tGrade = g ? gradeTheta(g.thetaDay, mid) : { label:'—', cls:'fair', note:'theta unavailable — IV missing' };
    var baseVerdict = overallVerdict([sGrade, dGrade, tGrade]);
    var verdict = applyNewsNudge(baseVerdict, input.news);

    var html = '';
    html += '<div class="opt-verdict ' + verdict.cls + '" id="opt-verdict-main">' + verdict.label + '</div>';
    html += verdictExplainer(verdict.cls);
    html += newsTakeHtml(input.news, input.ticker, verdict.nudged);
    html += '<div class="opt-contract">' + (input.label || '') + ' · spot $' + fmt(input.spot) + ' · ' + Math.max(0, Math.round(T*365)) + ' days to expiry</div>';
    html += '<div class="opt-grid">';
    html += row('Bid / Ask', '$' + fmt(bid) + ' / $' + fmt(ask));
    html += row('Mid', mid != null ? '$' + fmt(mid) : '—');
    html += row('Spread', spread != null ? ('$' + fmt(spread) + ' (' + fmtPct(spreadPct) + ')') : '—', gradeChip(sGrade), TIPS.spread);
    html += row('IV', iv != null ? fmtPct(iv*100) : '—', '', TIPS.iv);
    html += row('Delta', g ? fmt(g.delta, 3) : '—', g ? gradeChip(dGrade) : '', TIPS.delta);
    html += row('Theta / day', g ? '$' + fmt(g.thetaDay, 3) : '—', g ? gradeChip(tGrade) : '', TIPS.theta);
    html += row('Gamma', g ? fmt(g.gamma, 4) : '—', '', TIPS.gamma);
    html += row('Vega (per 1 vol pt)', g ? '$' + fmt(g.vega, 3) : '—', '', TIPS.vega);
    html += row('Open interest', input.oi != null ? String(input.oi) : '—');
    html += row('Volume', input.volume != null ? String(input.volume) : '—');
    html += '</div>';
    html += '<ul class="opt-notes">';
    html += '<li><b>Spread:</b> ' + sGrade.note + '.</li>';
    html += '<li><b>Delta:</b> ' + dGrade.note + '.</li>';
    html += '<li><b>Theta:</b> ' + tGrade.note + '.</li>';
    html += '</ul>';
    if (input.source === 'chain') {
      var payload = JSON.stringify({
        type: input.type, spot: input.spot, strike: input.strike, expEpoch: input.expEpoch,
        bid: input.bid, ask: input.ask, iv: input.iv,
        oi: input.oi, volume: input.volume,
      }).replace(/'/g, '&apos;');
      html += '<button type="button" class="opt-tweak-btn" data-tweak=\'' + payload + '\'>Tweak in manual form &darr;</button>';
    }
    var disc = input.source === 'manual'
      ? 'Greeks computed locally with Black-Scholes from your IV and a ' + (RFR*100).toFixed(1) + '% risk-free rate. You are the data source — only as accurate as the numbers you typed.'
      : 'Greeks computed with Black-Scholes from Yahoo&apos;s implied vol and a ' + (RFR*100).toFixed(1) + '% risk-free rate. Quotes are end-of-session as of the build timestamp shown above — for information only, not investment advice.';
    html += '<p class="opt-disclaimer">' + disc + '</p>';
    return { html: html, verdict: verdict, contractLabel: input.label || '' };
  }

  function renderStickyVerdict(verdict, label){
    var bar = $('opt-result-sticky');
    if (!bar) return;
    bar.innerHTML = '<span class="opt-verdict-mini ' + verdict.cls + '">' + verdict.label + '</span>' +
      '<span class="opt-contract-mini">' + escapeHtml(label) + '</span>';
  }
  function setupStickyObserver(){
    var verdictEl = $('opt-verdict-main');
    var bar = $('opt-result-sticky');
    if (!verdictEl || !bar || typeof IntersectionObserver === 'undefined') return;
    if (stickyIO) stickyIO.disconnect();
    stickyIO = new IntersectionObserver(function(entries){
      var e = entries[0];
      var stuck = !e.isIntersecting && e.boundingClientRect.top < 0;
      bar.hidden = !stuck;
    }, { threshold: 0, rootMargin: '-56px 0px 0px 0px' });
    stickyIO.observe(verdictEl);
  }

  function evaluate(){
    var c = findContract();
    var resultEl = $('opt-eval-result');
    var stickyEl = $('opt-result-sticky');
    if (!c){
      if (resultEl) resultEl.innerHTML = '';
      if (stickyEl){ stickyEl.hidden = true; stickyEl.innerHTML = ''; }
      return;
    }
    var type = getOptType();
    var label = (state.symbol || '') + ' ' + type.toUpperCase() + ' $' + fmt(c.s) + ' · exp ' + fmtExpiryLabel(state.currentExp);
    var built = buildResultHtml({
      type: type, spot: state.spot, strike: c.s, expEpoch: state.currentExp,
      bid: c.b, ask: c.a, last: c.l, iv: c.iv,
      oi: c.oi, volume: c.v, label: label, source: 'chain',
      news: state.news, ticker: state.symbol
    });
    resultEl.innerHTML = built.html;
    renderStickyVerdict(built.verdict, built.contractLabel);
    setupStickyObserver();
    setStatus('opt-eval-status', '', '');
  }
  var scheduleEvaluate = debounce(evaluate, 80);

  function evaluateManual(ev){
    if (ev) ev.preventDefault();
    var type = $('m-type').value;
    var spot = parseLoose($('m-spot').value);
    var strike = parseLoose($('m-strike').value);
    var expDateStr = $('m-expiry').value;
    var bid = parseLoose($('m-bid').value);
    var ask = parseLoose($('m-ask').value);
    var ivRaw = $('m-iv').value.trim();
    var oiRaw = $('m-oi').value.trim();
    var volRaw = $('m-vol').value.trim();
    var ivPct = parseLoose(ivRaw);
    var oi = parseLoose(oiRaw);
    var vol = parseLoose(volRaw);

    if (!(spot > 0))   { setStatus('opt-manual-status', 'Share price is required.', 'err'); return; }
    if (!(strike > 0)) { setStatus('opt-manual-status', 'Strike price is required.', 'err'); return; }
    if (!expDateStr)   { setStatus('opt-manual-status', 'Expiration date is required.', 'err'); return; }
    if (!isFinite(bid) || !isFinite(ask) || bid < 0 || ask < 0) { setStatus('opt-manual-status', 'Bid and ask are required (enter 0 if you have no quote).', 'err'); return; }
    if (ask < bid) { setStatus('opt-manual-status', 'Ask is below bid — check your numbers.', 'err'); return; }

    var expEpoch = Math.floor(new Date(expDateStr + 'T16:00:00-04:00').getTime()/1000);
    var label = type.toUpperCase() + ' $' + strike + ' · exp ' + expDateStr;
    var built = buildResultHtml({
      type: type, spot: spot, strike: strike, expEpoch: expEpoch,
      bid: bid, ask: ask, last: null,
      iv: (ivRaw && isFinite(ivPct) && ivPct >= 0) ? ivPct/100 : null,
      oi: (oiRaw && isFinite(oi)) ? Math.round(oi) : null,
      volume: (volRaw && isFinite(vol)) ? Math.round(vol) : null,
      label: label, source: 'manual'
    });
    $('opt-manual-result').innerHTML = built.html;
    setStatus('opt-manual-status', 'Graded.', 'ok');
  }

  function onPasteContract(){
    var input = $('m-paste');
    var hint = $('m-paste-hint');
    var raw = input.value;
    if (!raw || !raw.trim()){
      input.classList.remove('err');
      if (hint){ hint.textContent = ''; hint.classList.remove('err'); }
      return;
    }
    var parsed = parseOCC(raw);
    if (!parsed){
      input.classList.add('err');
      if (hint){ hint.textContent = "Doesn't look like an OCC symbol (e.g. AAPL250117C00150000)."; hint.classList.add('err'); }
      return;
    }
    input.classList.remove('err');
    $('m-type').value = parsed.type;
    $('m-strike').value = String(parsed.strike);
    $('m-expiry').value = parsed.expiryISO;
    if (hint){
      hint.textContent = 'Recognised: ' + parsed.root + ' ' + parsed.type.toUpperCase() + ' $' + parsed.strike + ' · exp ' + parsed.expiryISO;
      hint.classList.remove('err');
    }
  }

  function tweakInManual(payloadJson){
    if (!payloadJson) return;
    var p; try { p = JSON.parse(payloadJson); } catch (e) { return; }
    $('m-type').value = p.type === 'put' ? 'put' : 'call';
    if (p.spot != null)   $('m-spot').value   = String(p.spot);
    if (p.strike != null) $('m-strike').value = String(p.strike);
    if (p.expEpoch){
      var d = new Date(p.expEpoch*1000);
      var nyParts = new Intl.DateTimeFormat('en-CA', { timeZone:'America/New_York', year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(d);
      var y='', mo='', da='';
      for (var i=0; i<nyParts.length; i++){
        var part = nyParts[i];
        if (part.type === 'year') y = part.value;
        else if (part.type === 'month') mo = part.value;
        else if (part.type === 'day') da = part.value;
      }
      if (y && mo && da) $('m-expiry').value = y + '-' + mo + '-' + da;
    }
    if (p.bid != null) $('m-bid').value = String(p.bid);
    if (p.ask != null) $('m-ask').value = String(p.ask);
    $('m-iv').value  = (p.iv != null)     ? (p.iv*100).toFixed(2) : '';
    $('m-oi').value  = (p.oi != null)     ? String(p.oi)          : '';
    $('m-vol').value = (p.volume != null) ? String(p.volume)      : '';
    var paste = $('m-paste'); if (paste){ paste.value=''; paste.classList.remove('err'); }
    var hint = $('m-paste-hint'); if (hint){ hint.textContent=''; hint.classList.remove('err'); }
    evaluateManual();
    var section = $('opt-manual-section');
    if (section && section.scrollIntoView) section.scrollIntoView({ behavior:'smooth', block:'start' });
    $('m-bid').focus();
  }

  function fetchChain(symbol){
    if (CHAIN_CACHE[symbol]) return Promise.resolve(CHAIN_CACHE[symbol]);
    var v = (MANIFEST && MANIFEST.builtAtIso) ? '?v=' + encodeURIComponent(MANIFEST.builtAtIso) : '';
    return fetch('data/' + encodeURIComponent(symbol) + '.json' + v, { cache: 'force-cache' })
      .then(function(resp){
        if (!resp.ok) throw new Error('HTTP ' + resp.status);
        return resp.json();
      })
      .then(function(data){ CHAIN_CACHE[symbol] = data; return data; });
  }
  function loadChain(){
    var symbol = state.symbol; if (!symbol) return;
    var cached = !!CHAIN_CACHE[symbol];
    setStatus('opt-eval-status', cached ? '' : 'Loading ' + symbol + '…', '');
    fetchChain(symbol).then(function(entry){
      state.spot = entry.spot;
      state.expirations = (entry.expirations || []).slice();
      state.chains = entry.chains || {};
      state.news = entry.news || null;
      if (!state.expirations.length){ setStatus('opt-eval-status', 'No expirations for ' + symbol + '.', 'err'); return; }
      state.currentExp = state.expirations[0];
      populateExpiry();
      $('opt-expiry').value = String(state.currentExp);
      populateStrikes();
      $('opt-chain-row').hidden = false;
      renderTickerNarrativeChips(symbol);
      setStatus('opt-eval-status', symbol + ' · spot ' + fmtMoney(state.spot) + ' · ' + state.expirations.length + ' expirations', 'ok');
      evaluate();
    }).catch(function(err){
      setStatus('opt-eval-status', 'Failed to load ' + symbol + ': ' + (err && err.message || err), 'err');
    });
  }
  function onExpiryChange(){
    var exp = Number($('opt-expiry').value);
    state.currentExp = exp;
    populateStrikes();
    scheduleEvaluate();
  }

  // --- Narratives ---------------------------------------------------------
  function tickerChipHtml(sym, side){
    var sec = SECTORS[sym] || '';
    var titleAttr = sec ? ' title="' + escapeHtml(sec) + '"' : '';
    return '<span class="narr-chip ' + side + '"' + titleAttr + '>' + escapeHtml(sym) + '</span>';
  }
  function narrLifeLabel(n){
    var d = n.daysRunning | 0;
    if (!d || d <= 1) return 'New today';
    return 'Day ' + d;
  }
  function renderNarratives(){
    var list = $('narratives-list');
    var empty = $('narratives-empty');
    var ended = $('narratives-ended');
    var count = $('narratives-count');
    if (!list) return;
    if (count) count.textContent = NARRATIVES.length ? NARRATIVES.length + ' active' : '';
    if (!NARRATIVES.length){
      list.innerHTML = '';
      if (empty) empty.hidden = false;
    } else {
      if (empty) empty.hidden = true;
      list.innerHTML = NARRATIVES.map(function(n){
        var sent = n.sentiment === 'bearish' ? 'bearish' : 'bullish';
        var confLabel = ({ high:'High', medium:'Medium', low:'Low' })[n.confidence] || 'Medium';
        var longChips = (n.longs || []).map(function(t){ return tickerChipHtml(t, 'long'); }).join('');
        var shortChips = (n.shorts || []).map(function(t){ return tickerChipHtml(t, 'short'); }).join('');
        var longRow = longChips ? '<div class="narr-side-row long"><span class="narr-side-label">Long</span>' + longChips + '</div>' : '';
        var shortRow = shortChips ? '<div class="narr-side-row short"><span class="narr-side-label">Short</span>' + shortChips + '</div>' : '';
        return '<article class="narr" data-sent="' + sent + '" role="listitem">' +
          '<span class="narr-accent" aria-hidden="true"></span>' +
          '<header class="narr-head">' +
            '<h3 class="narr-name">' + escapeHtml(n.name) + '</h3>' +
            '<span class="narr-tag sent ' + sent + '">' + (sent === 'bullish' ? 'Bullish' : 'Bearish') + '</span>' +
            '<span class="narr-tag conf">Conf · ' + confLabel + '</span>' +
            '<span class="narr-life"><span class="narr-life-dot"></span>' + escapeHtml(narrLifeLabel(n)) + '</span>' +
          '</header>' +
          '<p class="narr-thesis">' + escapeHtml(n.thesis || '') + '</p>' +
          longRow + shortRow +
        '</article>';
      }).join('');
    }
    if (ended){
      if (RECENTLY_ENDED.length){
        ended.innerHTML = '<div class="narr-ended-head">Recently cooled off</div>' +
          '<div class="narr-ended-strip">' +
          RECENTLY_ENDED.map(function(e){
            var d = e.daysSince | 0;
            var ran = e.ranDays | 0;
            var ago = d === 1 ? 'yesterday' : d + ' days ago';
            var run = ran <= 1 ? 'one-day blip' : ran + '-day run';
            return '<div class="narr-ended-card">' +
              '<div class="narr-ended-name">' + escapeHtml(e.name) + '</div>' +
              '<div class="narr-ended-meta">' + ago + ' · ' + run + '</div>' +
            '</div>';
          }).join('') +
          '</div>';
      } else {
        ended.innerHTML = '';
      }
    }
  }
  function narrativesForTicker(sym){
    if (!sym) return [];
    var hits = [];
    for (var i=0; i<NARRATIVES.length; i++){
      var n = NARRATIVES[i];
      if ((n.longs || []).indexOf(sym) >= 0) hits.push({ n: n, side: 'long' });
      else if ((n.shorts || []).indexOf(sym) >= 0) hits.push({ n: n, side: 'short' });
    }
    return hits;
  }
  function renderTickerNarrativeChips(sym){
    var box = $('opt-narr-chips');
    if (!box) return;
    var hits = narrativesForTicker(sym);
    if (!hits.length){ box.hidden = true; box.innerHTML = ''; return; }
    box.hidden = false;
    box.innerHTML = '<span class="opt-narr-chips-label">Narratives</span>' + hits.map(function(h){
      var sentLabel = h.n.sentiment === 'bearish' ? 'Bearish' : 'Bullish';
      return '<span class="opt-narr-chip ' + h.side + '" title="' + escapeHtml(h.n.thesis || '') + '">' +
        escapeHtml(h.n.name) +
        '<span class="opt-narr-chip-side">' + h.side.toUpperCase() + ' · ' + sentLabel + '</span>' +
      '</span>';
    }).join('');
  }

  // --- Bind ---------------------------------------------------------------
  function bind(){
    renderFreshness();
    bindThemeToggle();
    combo.init();
    renderNarratives();

    var radioGroup = document.querySelector('[role="radiogroup"]');
    if (radioGroup){
      radioGroup.addEventListener('change', function(ev){
        if (ev.target && ev.target.name === 'opt-type'){
          if (state.currentExp) populateStrikes();
          scheduleEvaluate();
        }
      });
    }
    var expSel = $('opt-expiry');
    if (expSel) expSel.addEventListener('change', onExpiryChange);
    var strikeSel = $('opt-strike');
    if (strikeSel) strikeSel.addEventListener('change', scheduleEvaluate);

    var manualForm = $('opt-manual-form');
    if (manualForm){
      manualForm.addEventListener('submit', evaluateManual);
      var paste = $('m-paste');
      if (paste) paste.addEventListener('input', onPasteContract);
      var chainSection = $('opt-eval-section');
      if (chainSection){
        chainSection.addEventListener('click', function(ev){
          var btn = ev.target.closest && ev.target.closest('.opt-tweak-btn');
          if (!btn) return;
          tweakInManual(btn.getAttribute('data-tweak'));
        });
      }
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', bind);
  else bind();
})();
